import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import contract from '../electron_poc/community_folders_contract.js';
import clientModule from '../electron_poc/community_folders_client.js';

const folder={version:1,title:'Vex starter',creator:'Tester',description:'A curated set',folders:['','Shields','Empty'],items:[{name:'A',folder:'',serial:'@UCode'},{name:'A copy',folder:'Shields',serial:'@UCode'}]};
test('folder exports and imports preserve duplicates, hierarchy, and existing data',()=>{
  const original={folders:['Builds/Vex/Empty','Other'],bookmarks:[{name:'one',group:'Builds/Vex',serial:'@UAbCd'},{name:'two',group:'Builds / Vex / Shields',serial:'@UAbCd'},{name:'private',group:'Other',serial:'@USecret'}]};
  const exported=contract.exportFolder(original.bookmarks,original.folders,'Builds/Vex',{title:'Vex',creator:'Tester'});
  assert.equal(exported.items.length,2);assert.equal(exported.items[1].folder,'Shields');assert(exported.folders.includes('Empty'));
  const current={bookmarks:[{id:'old',name:'mine',serial:'@UKeep',group:'Vex'}],folders:['Vex']};
  const before=JSON.stringify(current),out=contract.importFolder(exported,current,()=>crypto.randomUUID());
  assert.equal(JSON.stringify(current),before);assert.equal(out.destination,'Vex (2)');assert.equal(out.bookmarks.length,3);assert.equal(out.bookmarks[1].serial,out.bookmarks[2].serial);assert(out.folders.includes('Vex (2) / Empty'));
  assert.throws(()=>contract.normalize({...folder,items:[{serial:'@Uone @Utwo'}]}));
  assert.throws(()=>contract.normalize({...folder,folders:['../bad']}));
  assert.equal(contract.normalize({...folder,items:[{name:'Long',serial:'@U'+'A'.repeat(99997)}]}).items[0].serial.length,99999);
});

test('real local D1: privacy, moderation, large payload, retry and safe local import data',async()=>{
  const compiled=await build({entryPoints:[new URL('./worker.js',import.meta.url).pathname.replace(/^\/([A-Za-z]:)/,'$1')],bundle:true,format:'esm',write:false,platform:'browser',external:['node:*'],loader:{'.html':'text'}});
  const admin=crypto.randomBytes(32).toString('hex');
  const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'library',modules:true,script:compiled.outputFiles[0].text,compatibilityDate:'2026-09-28',compatibilityFlags:['nodejs_compat'],d1Databases:{LIBRARY:'library'},bindings:{AUTH_SECRET:admin,PUBLIC_ORIGIN:'http://127.0.0.1:8789'}}]}));
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'msbt-community-'));
  try {
    const db=await mf.getD1Database('LIBRARY');
    const schema=await fs.readFile(new URL('./schema.sql',import.meta.url),'utf8')+';'+await fs.readFile(new URL('./auth-schema.sql',import.meta.url),'utf8');
    await db.batch(schema.split(';').filter(s=>s.trim()).map(s=>db.prepare(s)));
    let loseResponse=true;
    const fetcher=async(url,options)=>{const result=await mf.dispatchFetch(url,options);if(loseResponse&&new URL(url).pathname==='/submissions'){loseResponse=false;throw Error('Simulated lost response');}return result;};
    const safeStorage={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s).reverse(),decryptString:b=>Buffer.from(b).reverse().toString()};
    let client=clientModule.createCommunityClient({userData:dir,safeStorage,fetcher,endpoint:'http://127.0.0.1:8789'});
    await assert.rejects(client.dispatch('submit',{folder}),/lost response/);
    let mine=await client.dispatch('mine');assert.equal(mine.submissions.length,1);assert.equal(mine.submissions[0].status,'sending');assert(!JSON.stringify(mine).includes('secret'));
    const id=mine.submissions[0].id;
    assert.equal((await client.dispatch('list')).folders.length,0);
    assert.equal((await mf.dispatchFetch('http://local/folders/'+id)).status,404);
    assert.equal((await mf.dispatchFetch('http://local/share/'+id)).status,404);
    assert.equal((await mf.dispatchFetch('http://local/submissions/'+id)).status,404);
    assert.equal((await mf.dispatchFetch('http://local/review/'+id)).status,401);
    // Restart the desktop client: retained credentials and request give one server submission.
    client=clientModule.createCommunityClient({userData:dir,safeStorage,fetcher,endpoint:'http://127.0.0.1:8789'});
    await client.dispatch('retry',{id});
    assert.equal((await db.prepare('SELECT COUNT(*) n FROM folders').first()).n,1);
    assert.equal((await client.dispatch('status',{id})).status,'pending');
    const origin='http://127.0.0.1:8789';
    let cookie='';
    const request=async(route,method='GET',payload)=>mf.dispatchFetch(origin+route,{method,headers:{Origin:origin,...(cookie?{Cookie:cookie}:{}),...(payload?{'Content-Type':'application/json'}:{})},body:payload?JSON.stringify(payload):undefined});
    const signup=await request('/api/auth/sign-up/email','POST',{name:'Owner',email:'owner@example.test',password:'Test-only-strong-password-123!'});
    assert.equal(signup.status,200,await signup.clone().text());
    assert(signup.headers.getSetCookie().some(c=>/session_token=.*Max-Age=2592000/i.test(c)), 'remembered sign-in has a persistent 30-day cookie');
    cookie=signup.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');
    const owner=(await signup.json()).user;
    assert.equal((await request('/review')).status,401,'new account cannot review');
    await db.prepare("INSERT INTO team(user_id,role) VALUES(?,'owner')").bind(owner.id).run();
    const review=async(id,status,note='Reviewed')=>{const r=await request('/review/'+id);const data=await r.json();const out=await request('/review/'+id,'POST',{status,note,digest:data.digest});if(!out.ok)throw Error((await out.json()).message);return out.json();};
    assert.equal((await (await request('/review')).json()).folders.length,1);
    await review(id,'approved');
    const got=await client.dispatch('get',{id});assert.deepEqual(got.folder,folder);assert(!('owner_hash'in got));assert(!('review_note'in got));
    assert.equal((await client.dispatch('list',{q:'Vex'})).folders.length,1);
    await assert.rejects(client.dispatch('get',{id:'https://evil.test/folders/'+id}),/not an MSBT/);
    assert.equal((await mf.dispatchFetch('http://local/share/'+id)).status,200);
    await review(id,'rejected');
    assert.equal((await client.dispatch('list')).folders.length,0);
    await client.dispatch('withdraw',{id});
    await assert.rejects(review(id,'approved'),/withdrew/);
    const large={...folder,title:'Large',items:Array.from({length:3500},(_,i)=>({name:'Item '+i,folder:'',serial:'@U'+'AbC'.repeat(250)}))};
    assert(Buffer.byteLength(JSON.stringify(large))>2097152);
    const big=await client.dispatch('submit',{folder:large});
    const privateBig=await (await request('/review/'+big.id)).json();assert.equal(privateBig.folder.items.length,3500);assert.equal(privateBig.folder.items[3499].serial,large.items[3499].serial);
    const html={...folder,title:'<img src=x onerror=alert(1)>',description:'<script>alert(1)</script>'};
    const h=await client.dispatch('submit',{folder:html});await review(h.id,'approved');
    const page=await(await mf.dispatchFetch('http://local/share/'+h.id)).text();assert(!page.includes('<script>'));assert(page.includes('&lt;script&gt;'));
    const saved=await fs.readFile(path.join(dir,'community-folder-ownership.json'),'utf8');assert(!saved.includes(admin));
    const beforeEdit=await (await request('/review/'+h.id)).json();
    assert.equal((await request('/portal/api/folders/'+h.id,'PUT',{digest:'stale',folder})).status,409);
    assert.equal((await request('/portal/api/folders/'+h.id,'PUT',{digest:beforeEdit.digest,folder})).status,200);
    assert.equal((await mf.dispatchFetch(origin+'/folders/'+h.id)).status,404,'edits unpublish until approved');
    assert.equal((await (await request('/portal/api/audit')).json()).events.length>=4,true);
    const changed=await (await request('/review/'+h.id)).json();
    assert.equal((await request('/portal/api/folders/'+h.id,'DELETE',{digest:changed.digest})).status,200);
    assert.equal((await request('/review/'+h.id)).status,404);
    const forged=await mf.dispatchFetch(origin+'/review/'+big.id,{method:'POST',headers:{Cookie:cookie,Origin:'https://evil.test','Content-Type':'application/json'},body:JSON.stringify({status:'approved',digest:privateBig.digest})});
    assert.equal(forged.status,403,'cross-origin mutation denied');
    const ownerCookie=cookie;
    const teammate=await request('/api/auth/sign-up/email','POST',{name:'Teammate',email:'team@example.test',password:'Another-test-password-123!'});
    assert.equal(teammate.status,200);
    const teammateData=await teammate.json();
    cookie=teammate.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');
    assert.equal((await request('/portal/api/team','POST',{id:teammateData.user.id,role:'admin'})).status,403,'new user cannot self-promote');
    cookie=ownerCookie;
    assert.equal((await request('/portal/api/team','POST',{id:owner.id,role:'member'})).status,409,'owner cannot be demoted through portal');
    assert.equal((await request('/portal/api/team','POST',{id:teammateData.user.id,role:'editor'})).status,200);
    const login=await request('/api/auth/sign-in/email','POST',{email:'team@example.test',password:'Another-test-password-123!'});
    assert.equal(login.status,200);
    cookie=login.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');
    const editorCookie=cookie;
    assert.equal((await request('/review')).status,200,'editor can review');
    assert.equal((await request('/portal/api/team')).status,403,'editor cannot manage team');
    assert.equal((await request('/portal/api/folders/'+big.id,'DELETE',{digest:privateBig.digest})).status,403,'editor cannot delete folder');
    cookie=ownerCookie;
    await request('/portal/api/team','POST',{id:teammateData.user.id,role:'member'});
    cookie=editorCookie;
    assert.equal((await request('/review')).status,401,'revocation invalidates existing session');
    const storedPassword=await db.prepare('SELECT password FROM account WHERE userId=?').bind(teammateData.user.id).first();
    assert.notEqual(storedPassword.password,'Another-test-password-123!','passwords are hashed by auth library');
    cookie=ownerCookie;
    await request('/api/auth/sign-out','POST',{});
    assert.equal((await request('/review')).status,401,'logout revokes session');
  } finally {await mf.dispose();await fs.rm(dir,{recursive:true,force:true});}
});

