import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import contract from '../electron_poc/community_folders_contract.js';
import clientModule from '../electron_poc/community_folders_client.js';

const folder={version:1,title:'Vex starter',creator:'Tester',description:'A curated set',folders:['','Shields','Empty'],items:[{name:'A',folder:'',serial:'@UCode'},{name:'A copy',folder:'Shields',serial:'@UCode'}]};
test('folder exports and imports preserve duplicates, hierarchy, and existing data',()=>{
  const original={folders:['Builds/Vex/Empty','Other'],bookmarks:[{name:'one',group:'Builds/Vex',serial:'@UAbCd'},{name:'two',group:'Builds / Vex / Shields',serial:'@UAbCd'},{name:'private',group:'Other',serial:'@USecret'}]};
  const exported=contract.exportFolder(original.bookmarks,original.folders,'Builds/Vex',{title:'Vex',creator:'Tester'});
  assert.equal(exported.items.length,2);assert.equal(exported.items[1].folder,'Shields');assert(exported.folders.includes('Empty'));
  const current={bookmarks:[{id:'old',name:'mine',serial:'@UKeep',group:'Vex'}],folders:['Vex']};
  const before=JSON.stringify(current),out=contract.importFolder(exported,current,()=>crypto.randomUUID());
  assert.equal(JSON.stringify(current),before);assert.equal(out.destination,'Vex (2)');assert.equal(out.bookmarks.length,3);assert.equal(out.bookmarks[1].serial,out.bookmarks[2].serial);assert(out.folders.includes('Vex (2) / Empty'));
  assert.throws(()=>contract.normalize({...folder,items:[{serial:'@Uone @Utwo'}]}));
  assert.throws(()=>contract.normalize({...folder,folders:['../bad']}));
  assert.equal(contract.normalize({...folder,items:[{name:'Long',serial:'@U'+'A'.repeat(99997)}]}).items[0].serial.length,99999);
});

test('real local D1: privacy, moderation, large payload, retry and safe local import data',async()=>{
  const compiled=await build({entryPoints:[new URL('./worker.js',import.meta.url).pathname.replace(/^\/([A-Za-z]:)/,'$1')],bundle:true,format:'esm',write:false,platform:'browser',external:['node:*'],loader:{'.html':'text','.txt':'text'}});
  const admin=crypto.randomBytes(32).toString('hex');
  const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'library',modules:true,script:compiled.outputFiles[0].text,compatibilityDate:'2026-09-28',compatibilityFlags:['nodejs_compat'],d1Databases:{LIBRARY:'library'},bindings:{AUTH_SECRET:admin,PUBLIC_ORIGIN:'http://127.0.0.1:8789'}}]}));
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'msbt-community-'));
  try {
    const db=await mf.getD1Database('LIBRARY');
    const schema=await fs.readFile(new URL('./schema.sql',import.meta.url),'utf8')+';'+await fs.readFile(new URL('./auth-schema.sql',import.meta.url),'utf8');
    await db.batch(schema.split(';').filter(s=>s.trim()).map(s=>db.prepare(s)));
    const webOrigin='https://www.funkyoushift.com';
    const pf=await mf.dispatchFetch('http://local/submissions',{method:'OPTIONS',headers:{Origin:webOrigin}});
    assert.equal(pf.status,204);assert.equal(pf.headers.get('Access-Control-Allow-Origin'),webOrigin);assert.match(pf.headers.get('Access-Control-Allow-Headers'),/Authorization/);
    assert.equal((await mf.dispatchFetch('http://local/submissions',{method:'POST',headers:{Origin:'https://evil.example'}})).status,403);
    const webId=crypto.randomUUID(),webKey=crypto.randomBytes(32).toString('hex');
    const wr=method=>mf.dispatchFetch('http://local/submissions'+(method==='POST'?'':'/'+webId),{method,headers:{Origin:webOrigin,Authorization:'Bearer '+webKey,'Content-Type':'application/json'},body:method==='POST'?JSON.stringify({id:webId,folder}):undefined});
    for(let i=0;i<2;i++){const res=await wr('POST');assert(res.ok);assert.equal(res.headers.get('Access-Control-Allow-Origin'),webOrigin);}
    assert.equal((await (await wr('GET')).json()).status,'pending');assert.equal((await mf.dispatchFetch('http://local/folders/'+webId)).status,404);assert((await wr('DELETE')).ok);
    await db.prepare('DELETE FROM folder_chunks WHERE folder_id=?').bind(webId).run();await db.prepare('DELETE FROM folders WHERE id=?').bind(webId).run();
    for(const limit of ['0','101','1.5','bad'])assert.equal((await mf.dispatchFetch('http://local/folders?limit='+limit)).status,400);
    const pagingIds=Array.from({length:61},()=>crypto.randomUUID());
    await db.batch(pagingIds.map(id=>db.prepare("INSERT INTO folders(id,title,creator,description,item_count,oversized_count,digest,owner_hash,status,created_at) VALUES(?,'Paging','Test','',1,0,'digest','owner','approved','2026-10-01')").bind(id)));
    for(const limit of [25,50,100]){const data=await (await mf.dispatchFetch('http://local/folders?limit='+limit)).json();assert.equal(data.folders.length,Math.min(limit,61));assert.equal(data.next,limit<61?limit:null);if(data.next){const second=await(await mf.dispatchFetch('http://local/folders?limit='+limit+'&offset='+data.next)).json();assert(!second.folders.some(x=>data.folders.some(y=>y.id===x.id)));}}
    await db.batch(pagingIds.map(id=>db.prepare('DELETE FROM folders WHERE id=?').bind(id)));
    let loseResponse=true;
    const fetcher=async(url,options)=>{const result=await mf.dispatchFetch(url,options);if(loseResponse&&new URL(url).pathname==='/submissions'){loseResponse=false;throw Error('Simulated lost response');}return result;};
    const safeStorage={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s).reverse(),decryptString:b=>Buffer.from(b).reverse().toString()};
    let client=clientModule.createCommunityClient({userData:dir,safeStorage,fetcher,endpoint:'http://127.0.0.1:8789'});
    await assert.rejects(client.dispatch('submit',{folder}),/lost response/);
    let mine=await client.dispatch('mine');assert.equal(mine.submissions.length,1);assert.equal(mine.submissions[0].status,'sending');assert(!JSON.stringify(mine).includes('secret'));
    const id=mine.submissions[0].id;
    assert.equal((await client.dispatch('list')).folders.length,0);
    assert.equal((await mf.dispatchFetch('http://local/folders/'+id)).status,404);
    const privatePublicApi=await mf.dispatchFetch('http://local/api/v1/folders/'+id,{headers:{Origin:'https://another-app.example'}});
    assert.equal(privatePublicApi.status,404);
    assert.equal(privatePublicApi.headers.get('Access-Control-Allow-Origin'),'*');
    assert.equal((await (await mf.dispatchFetch('http://local/api/v1/folders')).json()).folders.length,0);
    assert.equal((await mf.dispatchFetch('http://local/share/'+id)).status,404);
    assert.equal((await mf.dispatchFetch('http://local/submissions/'+id)).status,404);
    assert.equal((await mf.dispatchFetch('http://local/review/'+id)).status,401);
    // Restart the desktop client: retained credentials and request give one server submission.
    client=clientModule.createCommunityClient({userData:dir,safeStorage,fetcher,endpoint:'http://127.0.0.1:8789'});
    await client.dispatch('retry',{id});
    assert.equal((await db.prepare('SELECT COUNT(*) n FROM folders').first()).n,1);
    assert.equal((await client.dispatch('status',{id})).status,'pending');
    const origin='http://127.0.0.1:8789';
    let cookie='';
    const request=async(route,method='GET',payload)=>mf.dispatchFetch(origin+route,{method,headers:{Origin:origin,...(cookie?{Cookie:cookie}:{}),...(payload?{'Content-Type':'application/json'}:{})},body:payload?JSON.stringify(payload):undefined});
    const signup=await request('/api/auth/sign-up/email','POST',{name:'Owner',email:'owner@example.test',password:'Test-only-strong-password-123!'});
    assert.equal(signup.status,200,await signup.clone().text());
    assert(signup.headers.getSetCookie().some(c=>/session_token=.*Max-Age=2592000/i.test(c)), 'remembered sign-in has a persistent 30-day cookie');
    cookie=signup.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');
    const owner=(await signup.json()).user;
    assert.equal((await request('/review')).status,401,'new account cannot review');
    await db.prepare("INSERT INTO team(user_id,role) VALUES(?,'owner')").bind(owner.id).run();
    // Screenshots use the same ownership and moderation boundary as the loadout.
    const mediaId=crypto.randomUUID(),mediaKey=crypto.randomBytes(32).toString('hex'),imageId=crypto.randomUUID();
    const uploadFolder=await mf.dispatchFetch(origin+'/submissions',{method:'POST',headers:{Authorization:'Bearer '+mediaKey,'Content-Type':'application/json'},body:JSON.stringify({id:mediaId,folder})});
    const mediaDigest=(await uploadFolder.json()).digest;
    const jpg=await fs.readFile(new URL('./fixtures/screenshot.jpg',import.meta.url));
    const screenshot={id:imageId,serial:folder.items[0].serial,data:jpg.toString('base64')};
    const uploadImages=(payload,key=mediaKey)=>mf.dispatchFetch(origin+'/submissions/'+mediaId+'/images',{method:'POST',headers:{Origin:'https://www.funkyoushift.com',Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({digest:mediaDigest,media_revision:0,images:[screenshot],...payload})});
    assert.equal((await uploadImages({},'f'.repeat(64))).status,403);
    assert.equal((await uploadImages({images:[{...screenshot,serial:folder.items[0].serial.toLowerCase()}]})).status,400);
    assert.equal((await uploadImages({images:[{...screenshot,data:Buffer.from('<svg/>').toString('base64')}]})).status,400);
    const imageResult=await uploadImages({});assert.equal(imageResult.status,200,await imageResult.clone().text());assert.equal((await imageResult.json()).media_revision,1);
    assert.equal((await (await uploadImages({})).json()).media_revision,1,'lost-response retry does not duplicate images or bump revision');
    assert.equal((await mf.dispatchFetch(origin+'/images/'+imageId)).status,404);
    const privateImage=await mf.dispatchFetch(origin+'/images/'+imageId,{headers:{Authorization:'Bearer '+mediaKey}});assert.equal(privateImage.status,200);assert.deepEqual(Buffer.from(await privateImage.arrayBuffer()),jpg);
    assert.equal((await request('/review/'+mediaId,'POST',{status:'approved',digest:mediaDigest,media_revision:0})).status,409,'review must include current screenshots');
    assert.equal((await request('/review/'+mediaId,'POST',{status:'approved',digest:mediaDigest,media_revision:1})).status,200);
    assert.equal((await mf.dispatchFetch(origin+'/images/'+imageId)).headers.get('Content-Type'),'image/jpeg');
    const withImage=await(await mf.dispatchFetch(origin+'/folders/'+mediaId)).json();assert.equal(withImage.images[0].serial_hash,crypto.createHash('sha256').update(screenshot.serial).digest('hex'));assert.equal(withImage.item_details[withImage.images[0].serial_hash].image_url,origin+'/images/'+imageId);
    const changedImage={...screenshot,id:crypto.randomUUID()};
    assert.equal((await uploadImages({media_revision:1,images:[changedImage]})).status,200);
    assert.equal((await mf.dispatchFetch(origin+'/folders/'+mediaId)).status,404,'replacing image requires approval again');
    assert.equal((await mf.dispatchFetch(origin+'/images/'+imageId)).status,404,'replaced image is gone');
    assert.equal((await request('/review/'+mediaId,'POST',{status:'approved',digest:mediaDigest,media_revision:1})).status,409);
    await db.prepare('DELETE FROM item_images WHERE folder_id=?').bind(mediaId).run();await db.prepare('DELETE FROM folder_chunks WHERE folder_id=?').bind(mediaId).run();await db.prepare('DELETE FROM folders WHERE id=?').bind(mediaId).run();
    const review=async(id,status,note='Reviewed')=>{const r=await request('/review/'+id);const data=await r.json();const out=await request('/review/'+id,'POST',{status,note,digest:data.digest});if(!out.ok)throw Error((await out.json()).message);return out.json();};
    assert.equal((await (await request('/review')).json()).folders.length,1);
    await review(id,'approved');
    const got=await client.dispatch('get',{id});assert.deepEqual(got.folder,folder);assert(!('owner_hash'in got));assert(!('review_note'in got));
    assert.equal((await client.dispatch('list',{q:'Vex'})).folders.length,1);
    const publicList=await mf.dispatchFetch('http://local/api/v1/folders?q=Vex',{headers:{Origin:'https://another-app.example'}});
    assert.equal(publicList.headers.get('Access-Control-Allow-Origin'),'*');
    assert.equal(publicList.headers.get('Access-Control-Allow-Credentials'),null);
    assert.equal((await publicList.json()).folders.length,1);
    const publicDetail=await (await mf.dispatchFetch('http://local/api/v1/folders/'+id)).json();
    assert.deepEqual(publicDetail.folder,folder);
    assert.equal(publicDetail.digest,got.digest);
    assert(!('owner_hash' in publicDetail));assert(!('review_note' in publicDetail));
    for(const method of ['POST','PUT','DELETE'])assert.equal((await mf.dispatchFetch('http://local/api/v1/folders/'+id,{method})).status,405);
    const preflight=await mf.dispatchFetch('http://local/api/v1/folders',{method:'OPTIONS',headers:{Origin:'https://another-app.example','Access-Control-Request-Method':'GET'}});
    assert.equal(preflight.status,204);assert.equal(preflight.headers.get('Access-Control-Allow-Origin'),'*');
    assert.equal((await mf.dispatchFetch('http://local/api/v1/review')).status,404);
    assert.equal((await mf.dispatchFetch('http://local/api/v1/submissions/'+id)).status,404);
    const spec=await (await mf.dispatchFetch('http://local/api/v1/openapi.json')).json();
    assert.equal(spec.openapi,'3.1.0');assert(spec.paths['/folders/{id}']);
    for(const origin of ['https://www.funkyoushift.com','https://funkyoushift.com','https://funkyoushift.github.io']) {
      for(const route of ['/folders','/folders/'+id]) {
        const response=await mf.dispatchFetch('http://local'+route,{headers:{Origin:origin}});
        assert.equal(response.headers.get('Access-Control-Allow-Origin'),origin);
        assert.equal(response.headers.get('Access-Control-Allow-Credentials'),null);
      }
    }
    for(const route of ['/review','/portal/api/me']) {
      assert.equal((await mf.dispatchFetch('http://local'+route,{headers:{Origin:'https://www.funkyoushift.com'}})).headers.get('Access-Control-Allow-Origin'),null);
    }
    assert.equal((await mf.dispatchFetch('http://local/folders',{headers:{Origin:'https://untrusted.example'}})).headers.get('Access-Control-Allow-Origin'),null);
    assert.equal((await mf.dispatchFetch('http://local/submissions',{method:'POST',headers:{Origin:'https://www.funkyoushift.com'}})).status,401);
    await assert.rejects(client.dispatch('get',{id:'https://evil.test/folders/'+id}),/not an MSBT/);
    assert.equal((await mf.dispatchFetch('http://local/share/'+id)).status,200);
    await review(id,'rejected');
    assert.equal((await client.dispatch('list')).folders.length,0);
    await client.dispatch('withdraw',{id});
    await assert.rejects(review(id,'approved'),/withdrew/);
    const large={...folder,title:'Large',items:Array.from({length:3500},(_,i)=>({name:'Item '+i,folder:'',serial:'@U'+'AbC'.repeat(250)}))};
    assert(Buffer.byteLength(JSON.stringify(large))>2097152);
    const big=await client.dispatch('submit',{folder:large});
    const privateBig=await (await request('/review/'+big.id)).json();assert.equal(privateBig.folder.items.length,3500);assert.equal(privateBig.folder.items[3499].serial,large.items[3499].serial);
    const html={...folder,title:'<img src=x onerror=alert(1)>',description:'<script>alert(1)</script>'};
    const h=await client.dispatch('submit',{folder:html});await review(h.id,'approved');
    const page=await(await mf.dispatchFetch('http://local/share/'+h.id)).text();assert(!page.includes('<script>'));assert(page.includes('&lt;script&gt;'));
    const saved=await fs.readFile(path.join(dir,'community-folder-ownership.json'),'utf8');assert(!saved.includes(admin));
    const beforeEdit=await (await request('/review/'+h.id)).json();
    assert.equal((await request('/portal/api/folders/'+h.id,'PUT',{digest:'stale',folder})).status,409);
    assert.equal((await request('/portal/api/folders/'+h.id,'PUT',{digest:beforeEdit.digest,folder})).status,200);
    assert.equal((await mf.dispatchFetch(origin+'/folders/'+h.id)).status,404,'edits unpublish until approved');
    assert.equal((await (await request('/portal/api/audit')).json()).events.length>=4,true);
    const changed=await (await request('/review/'+h.id)).json();
    assert.equal((await request('/portal/api/folders/'+h.id,'DELETE',{digest:changed.digest})).status,200);
    assert.equal((await request('/review/'+h.id)).status,404);
    const forged=await mf.dispatchFetch(origin+'/review/'+big.id,{method:'POST',headers:{Cookie:cookie,Origin:'https://evil.test','Content-Type':'application/json'},body:JSON.stringify({status:'approved',digest:privateBig.digest})});
    assert.equal(forged.status,403,'cross-origin mutation denied');
    const ownerCookie=cookie;
    const teammate=await request('/api/auth/sign-up/email','POST',{name:'Teammate',email:'team@example.test',password:'Another-test-password-123!'});
    assert.equal(teammate.status,200);
    const teammateData=await teammate.json();
    cookie=teammate.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');
    assert.equal((await request('/portal/api/team','POST',{id:teammateData.user.id,role:'admin'})).status,403,'new user cannot self-promote');
    cookie=ownerCookie;
    assert.equal((await request('/portal/api/team','POST',{id:owner.id,role:'member'})).status,409,'owner cannot be demoted through portal');
    assert.equal((await request('/portal/api/team','POST',{id:teammateData.user.id,role:'editor'})).status,200);
    const login=await request('/api/auth/sign-in/email','POST',{email:'team@example.test',password:'Another-test-password-123!'});
    assert.equal(login.status,200);
    cookie=login.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');
    const editorCookie=cookie;
    assert.equal((await request('/review')).status,200,'editor can review');
    assert.equal((await request('/portal/api/team')).status,403,'editor cannot manage team');
    assert.equal((await request('/portal/api/folders/'+big.id,'DELETE',{digest:privateBig.digest})).status,403,'editor cannot delete folder');
    cookie=ownerCookie;
    await request('/portal/api/team','POST',{id:teammateData.user.id,role:'member'});
    cookie=editorCookie;
    assert.equal((await request('/review')).status,401,'revocation invalidates existing session');
    const storedPassword=await db.prepare('SELECT password FROM account WHERE userId=?').bind(teammateData.user.id).first();
    assert.notEqual(storedPassword.password,'Another-test-password-123!','passwords are hashed by auth library');
    cookie=ownerCookie;
    await request('/api/auth/sign-out','POST',{});
    assert.equal((await request('/review')).status,401,'logout revokes session');
  } finally {await mf.dispose();await fs.rm(dir,{recursive:true,force:true});}
});

