// Only actions exposed by the phone controller. The SDK retains its normal
// target, host, delivery-queue and shared-operation checks while AFK is running.
const ACTIONS=new Set(`
afk_lobby_start afk_lobby_stop shift_overlay_control set_target_player refresh_players
max_all max_currency max_eridium max_player_level max_spec_level max_sdu give_currency set_level
give_serial_selected give_serial_all give_serial_nonhost repeat_last_drop
set_backpack_bank_selected set_backpack_bank_all shiny_selected shiny_all shiny_nonhost drop_all_shinies
read_inventory read_equipped_serials read_backpack_serials
movement_apply_all movement_azzy_super_dash movement_azzy_super_dash_toggle
movement_delete_ground_items movement_hide_ground_loot movement_pull_ground_loot
movement_infinite_jump_all_off movement_infinite_jump_all_on movement_infinite_jump_selected_off
movement_infinite_jump_selected_on movement_infinite_jump_toggle_selected movement_players_only
movement_preset_fast movement_preset_fastglide movement_preset_moon movement_preset_veryfast
movement_preset_wallwalk movement_reset_all movement_reset_time movement_set_time movement_super_dash
movement_super_dash_toggle movement_teleport_to_slot movement_toggle_no_target movement_toggle_noclip movement_zero_vault
rarity_apply rarity_only_legendary rarity_only_pearlescent rarity_reset
cxp_toggle instant_drops_toggle instant_holds_toggle third_person_toggle
open_bank open_golden_chest close_golden_chest spawn_golden_chest
spawn_black_market black_market_status black_market_clear_cooldown open_firmware_transfer reset_skills
teleport_debug_cam toggle_debug_cam travel_to_map travel_to_station spawn_itempool
location_bookmark_list location_bookmark_save location_bookmark_go location_bookmark_delete
uvh_boost_all uvh_boost_cancel uvh_boost_status uvh_boost_resume
uvh_boost_tier_1 uvh_boost_tier_2 uvh_boost_tier_3 uvh_boost_tier_4 uvh_boost_tier_5 uvh_boost_tier_6 uvh_boost_tier_7
challenge_catalog_list complete_challenges complete_challenges_all complete_challenges_cancel complete_challenges_status
quick_menu_get_layout quick_menu_assign_slot quick_menu_clear_page quick_menu_set_layout
hoard_clear hoard_set_plan hoard_start hoard_status hoard_stop
devperk_0 devperk_1 devperk_2 devperk_3 devperk_4 devperk_5 devperk_6 devperk_7
dev_spawner_activate_last dev_spawner_barrel_logo dev_spawner_cache dev_spawner_cache_status
dev_spawner_clear dev_spawner_logo_options dev_spawner_lostloot dev_spawner_probeai dev_spawner_scriptdump
dev_spawner_spawn dev_spawner_spawnai dev_spawner_spawnerdiag dev_spawner_status dev_spawner_targets
`.trim().split(/\s+/));
const STATUS_FIELDS=`ok name started message players selected_player selected_player_index host_player_index
player_readback game_parameters afk_lobby serial_delivery challenge_bulk itempool_bulk uvh_boost
rarity_weights rarity_revision cxp instant_drops instant_holds third_person location_bookmarks`.split(/\s+/);
function phoneStatus(data){
  const result={remote_commands_supported:true};
  for(const field of STATUS_FIELDS)if(Object.hasOwn(data,field))result[field]=data[field];
  return result;
}
module.exports={ACTIONS,phoneStatus};
