const assert = require('assert/strict');
const fs = require('fs/promises');
const os = require('os');
const path = require('path');
const {app, BrowserWindow} = require('electron');
const store = require('./serial_bookmarks_store');
app.disableHardwareAcceleration();
app.whenReady().then(async()=>{
  const dir = await fs.mkdtemp(path.join(os.tmpdir(),'msbt-folders-'));
  const file = path.join(dir,'serial_bookmarks.json');
  const rows = [{id:'a',name:'Same',group:'Old group',serial:'@Uone'}, {id:'b',name:'Same',group:'Old group',serial:'@Uone'}];
  const saved = await store.writeBookmarks(file,{bookmarks:rows,folders:['Empty / Nested']});
  assert.equal(saved.data.bookmarks.length,2);
  await store.writeBookmarks(file,{bookmarks:saved.data.bookmarks});
  assert.ok((await store.readBookmarks(file)).data.folders.includes('Empty / Nested'));
  const win = new BrowserWindow({show:false,webPreferences:{sandbox:false,partition:'folder-test-'+process.pid}});
  await win.loadFile(path.join(__dirname,'renderer.html'),{query:{nosplash:'1'}});
  const result = await win.webContents.executeJavaScript(`(async()=>{
    const check=(value,message)=>{if(!value)throw Error(message)};
    let persisted;
    window.msbt=window.msbt||{};
    window.msbt.saveSerialBookmarks=async data=>{persisted=JSON.parse(JSON.stringify(data));return {ok:true,data:persisted}};
    state.bookmarks=[{id:'a',name:'Gun',group:'Weapons / Shotguns',serial:'@Uone'},{id:'b',name:'Shield',group:'Shields',serial:'@Utwo'}];
    state.bookmarkFolders=['Empty / Child'];state.bookmarkCheckedIds=new Set(['a']);renderBookmarks();
    els.bookmarkGroupFilter.value='Weapons';renderBookmarks();
    check(state.bookmarkVisibleRows.length===1,'parent should include child items');
    document.getElementById('bookmarkFolderPath').value='Builds / Vex / Starter';
    await manageBookmarkFolder(true);
    check(persisted.bookmarks[0].group==='Builds / Vex / Starter','move');
    check(persisted.bookmarks[0].serial==='@Uone'&&persisted.bookmarks[1].group==='Shields','preserve unrelated bookmarks');
    check(bookmarkGroups().includes('Builds / Vex'),'ancestor');
    document.getElementById('bookmarkFolderPath').value='Another / Empty';await manageBookmarkFolder(false);
    check(persisted.folders.includes('Another / Empty'),'empty folder saved');
    const before=JSON.stringify(state.bookmarks);
    window.msbt.saveSerialBookmarks=async()=>({ok:false,message:'Disk failure'});
    document.getElementById('bookmarkFolderPath').value='Failed';await manageBookmarkFolder(true);
    check(JSON.stringify(state.bookmarks)===before&&!state.bookmarkFolders.includes('Failed'),'failed save rollback');
    return true;
  })()`);
  assert.ok(result);win.destroy();console.log('PASS nested folders, parent filtering, empty-folder persistence, migration, move and rollback');app.exit(0);
}).catch(error=>{console.error(error);app.exit(1)});
