"use strict";
const assert = require("assert");
const path = require("path");
const fs = require("fs");
const { app, BrowserWindow } = require("electron");
app.disableHardwareAcceleration();
app.whenReady().then(async () => {
  const win = new BrowserWindow({ show: false, width: 1300, height: 1000, webPreferences: { sandbox: false, partition: `afk-${process.pid}` } });
  await win.loadFile(path.join(__dirname, "renderer.html"), { query: { nosplash: "1" } });
  const results = await win.webContents.executeJavaScript(`(async () => {
    const calls = [];
    window.msbt = window.msbt || {};
    window.msbt.loadSerialBookmarks = async () => ({ok:true,data:{bookmarks:[{name:"Test bookmark",group:"Test",serial:"@Ufixture"}]}});
    bridgeAction = async (action,payload) => {
      calls.push({action,payload});
      return {ok:true,data:{ok:true,afk_lobby:{enabled:action==='afk_lobby_start',message:action==='afk_lobby_start'?'Running':'Stopped',config:payload,history:[]}}};
    };
    bridgeStatus = async () => {};
    window.msbtAfkRender({afk_lobby:{enabled:false,host_test_supported:true,message:'Stopped'}});
    document.querySelector('[data-afk-boost="loot"]').checked = true;
    document.getElementById('afkCodes').value = '';
    document.getElementById('afkGuaranteedCodes').value = '';
    document.getElementById('afkTestHost').click();
    await new Promise(resolve=>setTimeout(resolve,30));
    if (calls.length || !document.getElementById('afkStatus').textContent.includes('both loot lists are empty')) throw Error('Empty loot host test was not explained before dispatch');
    for (let i=0;i<3;i++) window.msbtAfkRender({afk_lobby:{enabled:false,host_test_supported:true,message:'Stopped'}});
    if (!document.getElementById('afkStatus').textContent.includes('both loot lists are empty')) throw Error('Polling hid host-test validation failure');
    if (document.getElementById('afkTestHost').disabled) throw Error('Validation failure prevented retry');
    window.msbtAfkRender({afk_lobby:{enabled:false,message:'Stopped',loot_modes:['all','random70'],guaranteed_loot_supported:true,item_level_override_supported:true,history:[],shift_connected:true,shift_running:false}});
    document.getElementById('afkLoadBookmarks').click();
    await new Promise(resolve=>setTimeout(resolve,30));
    document.getElementById('afkBookmarks').options[0].selected = true;
    document.getElementById('afkAddBookmarks').click();
    const codes = document.getElementById('afkCodes').value;
    state.bl4Entries = [{id:'a',serial:'@UCatalogAlpha',name:'Alpha'},{id:'b',serial:'@UCatalogBeta',name:'Beta'}];
    state.bl4SelectedIds = new Set(['a','b']);
    state.bl4ActiveId = 'a';
    document.getElementById('bl4AddToAfkBtn').click();
    document.getElementById('bl4AddThisToAfkBtn').click();
    document.getElementById('bl4AddGuaranteedAfkBtn').click();
    const guaranteedCodes = document.getElementById('afkGuaranteedCodes').value;
    const catalogCodes = document.getElementById('afkCodes').value;
    const savedCodes = JSON.parse(localStorage.getItem('msbt.afk-lobby.v1')).codes;
    const kickDefaultOff = !document.getElementById('afkAutoKick').checked;
    const newOptions = ['uvhm', 'cosmetics'].map(key => document.querySelector('[data-afk-boost="'+key+'"]'));
    const newDefaultsOff = newOptions.every(node => node && !node.checked);
    newOptions.forEach(node => { node.checked = true; });
    document.getElementById('afkAutoKick').checked = true;
    document.getElementById('afkKickExemptNames').value = 'FriendOne\\nFriendTwo';
    document.querySelector('[data-afk-boost="vault_levels"]').checked = true;
    document.querySelector('[data-afk-boost="vault_levels"]').closest('.afk-amount').querySelector('input[type=number]').value = '250';
    document.getElementById('afkCleanupRewards').checked = true;
    const lootMode = document.getElementById('afkLootMode');
    const unlimitedDefault = lootMode.value === 'all';
    if (document.getElementById('afkItemLevelOverride').checked) throw Error('Override must default off');
    document.getElementById('afkItemLevelOverride').checked = true;
    document.getElementById('afkItemLevel').value = '35';
    lootMode.value = 'random70';
    lootMode.dispatchEvent(new Event('change', {bubbles:true}));
    const savedMode = JSON.parse(localStorage.getItem('msbt.afk-lobby.v1')).loot_mode;
    window.msbtAfkRender({afk_lobby:{enabled:false,message:'Old SDK',history:[]}});
    document.getElementById('afkStart').click();
    await new Promise(resolve=>setTimeout(resolve,30));
    const oldSdkBlocked = calls.length === 0 && document.getElementById('afkStatus').textContent.includes('updated SDK');
    window.msbtAfkRender({afk_lobby:{enabled:false,message:'Ready',boost_amounts_supported:true,kick_exempt_names_supported:true,vault_card_levels_supported:true,cleanup_rewards_supported:true,loot_modes:['all','random70'],guaranteed_loot_supported:true,item_level_override_supported:true,history:[]}});
    document.getElementById('afkStart').click();
    await new Promise(resolve=>setTimeout(resolve,30));
    const locked = document.getElementById('afkCodes').disabled && lootMode.disabled && document.getElementById('afkGuaranteedCodes').disabled;
    const stopEnabled = !document.getElementById('afkStop').disabled;
    document.getElementById('bl4AddToAfkBtn').click();
    const unchangedWhileRunning = document.getElementById('afkCodes').value === catalogCodes;
    document.getElementById('afkStop').click();
    await new Promise(resolve=>setTimeout(resolve,30));
    const unlocked = !document.getElementById('afkCodes').disabled && !lootMode.disabled;
    window.msbtAfkRender({afk_lobby:{enabled:false,message:'Ready for testing â€” select boosts, then Start AFK Lobby.',history:[],shift_connected:true,shift_running:false}});
    const panel = document.getElementById('afkLobbyPanel');
    document.querySelector('[data-workspace-local-section="afk"]').click();
    document.getElementById('msbtBootSplash').style.display = 'none';
    if (getComputedStyle(panel).display === 'none') throw new Error('AFK navigation did not reveal panel');
    panel.scrollIntoView();
    document.getElementById('afkCloseShift').click();
    await new Promise(resolve => setTimeout(resolve, 20));
    if (!document.getElementById('afkTestHost').disabled) throw new Error('Old SDK must not offer host test');
    const amounts = {level:30,spec:50,cash:1250,eridium:100,keys:5};
    for (const [key, value] of Object.entries(amounts)) {
      const group = document.querySelector('[data-afk-boost="'+key+'"]').closest('.afk-amount');
      const slider = group.querySelector('[type="range"]'), number = group.querySelector('[type="number"]');
      slider.value = value; slider.dispatchEvent(new Event('input', {bubbles:true}));
      if (Number(number.value) !== value) throw Error('Slider did not update exact amount: '+key);
      number.dispatchEvent(new Event('change', {bubbles:true}));
    }
    document.getElementById('afkStart').click();
    await new Promise(resolve => setTimeout(resolve, 30));
    if (calls.length !== 3 || !document.getElementById('afkStatus').textContent.includes('custom AFK boost amounts')) throw Error('Old SDK accepted custom amounts');
    const savedAmounts = JSON.parse(localStorage.getItem('msbt.afk-lobby.v1'));
    for (const [key, value] of Object.entries(amounts)) if(savedAmounts[key+'_amount'] !== value) throw Error('Amount was not saved: '+key);
    await window.msbtAfkConfigStore.save(savedAmounts);
    const durableAmounts = await window.msbtAfkConfigStore.load();
    for (const [key, value] of Object.entries(amounts)) if(durableAmounts[key+'_amount'] !== value) throw Error('Amount lost in durable store: '+key);
    window.msbtAfkRender({afk_lobby:{enabled:false,boost_amounts_supported:true,kick_exempt_names_supported:true,vault_card_levels_supported:true,host_test_supported:true,cleanup_rewards_supported:true,loot_modes:['all','random70'],guaranteed_loot_supported:true,item_level_override_supported:true,history:[]}});
    document.getElementById('afkTestHost').click();
    await new Promise(resolve => setTimeout(resolve, 30));
    if (!document.getElementById('afkTestHost').disabled) throw new Error('Host test must lock while running');
    return {guaranteedCodes,oldSdkBlocked,unlimitedDefault,savedMode,calls,codes,catalogCodes,savedCodes,kickDefaultOff,newDefaultsOff,unchangedWhileRunning,locked,unlocked,stopEnabled,hasSduLabel:panel.textContent.includes('3,225')};
  })()`);
  assert.equal(results.codes, "@Ufixture");
  assert.equal(results.catalogCodes, "@Ufixture\n@UCatalogAlpha\n@UCatalogBeta\n@UCatalogAlpha");
  assert.equal(results.savedCodes, results.catalogCodes);
  assert(results.unchangedWhileRunning);
  assert.equal(results.calls[0].action, "afk_lobby_start");
  assert.equal(results.calls[0].payload.serial_override_level, true);
  assert.equal(results.calls[0].payload.serial_level, 35);
  assert.equal(results.calls[0].payload.sdu, true);
  assert.equal(results.calls[0].payload.loot, true);
  assert.equal(results.calls[0].payload.auto_accept, true);
  assert(results.kickDefaultOff);
  assert(results.newDefaultsOff);
  assert(results.unlimitedDefault);
  assert(results.oldSdkBlocked);
  assert.equal(results.savedMode, 'random70');
  assert.equal(results.calls[0].payload.loot_mode, 'random70');
  assert.equal(results.guaranteedCodes, '@UCatalogAlpha\n@UCatalogBeta');
  assert.equal(results.calls[0].payload.guaranteed_codes, results.guaranteedCodes);
  assert.equal(results.calls[0].payload.challenges, false);
  for (const key of ['uvhm', 'cosmetics']) assert.equal(results.calls[0].payload[key], true);
  assert.equal(results.calls[0].payload.auto_kick, true);
  assert.equal(results.calls[0].payload.kick_exempt_names, 'FriendOne\nFriendTwo');
  assert.equal(results.calls[0].payload.vault_levels, true);
  assert.equal(results.calls[0].payload.vault_levels_amount, 250);
  assert.equal(results.calls[0].payload.cleanup_rewards, true);
  assert.equal(results.calls[1].action, "afk_lobby_stop");
  assert.equal(results.calls[2].action, "shift_overlay_control");
  assert.equal(results.calls[2].payload.mode, "close");
  assert.equal(results.calls[3].action, 'afk_lobby_start');
  assert.equal(results.calls[3].payload.test_host, true);
  for (const [key,value] of Object.entries({level:30,spec:50,cash:1250,eridium:100,keys:5})) assert.equal(results.calls[3].payload[key+'_amount'], value);
  assert.equal(results.calls[3].payload.codes, results.catalogCodes);
  assert.equal(results.calls[3].payload.guaranteed_codes, results.guaranteedCodes);
  assert(results.locked && results.unlocked && results.stopEnabled && results.hasSduLabel);
  const out = path.join(__dirname, "../output/afk-lobby");
  fs.mkdirSync(out, { recursive: true });
  win.show();
  await new Promise(resolve => setTimeout(resolve, 600));
  await win.webContents.executeJavaScript(`document.getElementById('walkthroughModal')?.remove(); document.getElementById('walkthroughCard')?.remove(); document.getElementById('msbtBootSplash')?.remove(); document.getElementById('afkLobbyPanel').scrollIntoView();`);
  await new Promise(resolve => setTimeout(resolve, 200));
  fs.writeFileSync(path.join(out, "panel.png"), (await win.webContents.capturePage()).toPNG());
  console.log("PASS AFK UI: bookmarks, start payload, fixed SDU control, edit lock, stop, screenshot.");
  win.destroy(); app.exit(0);
}).catch(error => { console.error(error); app.exit(1); });
