const {app,BrowserWindow,protocol}=require('electron');
const {registerNativeCardSchemes,installNativeCardProtocol}=require('./native_card_protocol');
registerNativeCardSchemes(protocol);
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
app.disableHardwareAcceleration();
app.whenReady().then(async()=>{
 const win=new BrowserWindow({width:1400,height:1000,show:false,webPreferences:{partition:'community-ui-'+process.pid}});
 installNativeCardProtocol(win.webContents.session.protocol);
 await win.loadFile(path.join(__dirname,'renderer.html'),{query:{nosplash:'1'}});
 const result=await win.webContents.executeJavaScript(`(async()=>{
  const check=(v,m)=>{if(!v)throw Error(m)},$=id=>document.getElementById(id);
  await runBootSplash();
  const idle=async()=>{for(let i=0;i<100&&$('communityFoldersPanel').getAttribute('aria-busy')==='true';i++)await new Promise(r=>setTimeout(r,10));};
  state.bookmarks=[{id:'old',name:'Keep me',serial:'@UKeep',group:'Mine'},{id:'a',name:'A',serial:'@UAbCd',group:'Builds / Vex'},{id:'b',name:'B',serial:'@UAbCd',group:'Builds / Vex / Shields'}];state.bookmarkFolders=['Mine','Builds / Vex','Builds / Vex / Shields'];renderBookmarks();
  $('bookmarkGroupFilter').value='Mine';$('bookmarkGroupFilter').dispatchEvent(new Event('change'));
  check($('bookmarkRows').querySelectorAll('.bookmark-row').length===1,'folder dropdown filters Mine');
  state.bookmarkCheckedIds.add('old');state.bookmarkActiveId='old';
  $('bookmarkGroupFilter').value='Builds / Vex';$('bookmarkGroupFilter').dispatchEvent(new Event('change'));
  check($('bookmarkRows').querySelectorAll('.bookmark-row').length===2,'folder shows subtree');
  check(bookmarkSelectedEntries().length===0,'switch clears old folder selection');
  $('bookmarkSelectAllBtn').click();check(bookmarkSelectedEntries().length===2,'select all local');
  $('bookmarkClearSelectedBtn').click();check(bookmarkSelectedEntries().length===0,'clear means no delivery');
  let sent,imported=false,calls=[];
  const folder={version:1,title:'Vex starter',creator:'Community tester',description:'Gun and shield drop list',folders:['','Shields'],items:[{name:'<img src=x onerror=alert(1)>',folder:'',serial:'@UAbCd'},{name:'Shield',folder:'Shields',serial:'@UAbCd'}]};
  window.msbt=window.msbt||{};
  window.msbt.communityFolders=async(op,p)=>{calls.push(op);
   if(op==='info')return {ok:true,endpoint:'https://library.example'};
   if(op==='list')return {ok:true,next:null,folders:[{id:'demo',title:folder.title,creator:folder.creator,item_count:2,status:'approved'}]};
   if(op==='get')return {ok:true,id:'demo',status:'approved',digest:'test',folder};
   if(op==='submit'){sent=p.folder;return {ok:true,status:'pending',id:'pending-demo'};}
   if(op==='import'){imported=true;return {ok:true,imported:2,destination:'Vex starter',data:window.communityFolderContract.importFolder(folder,{bookmarks:state.bookmarks,folders:state.bookmarkFolders},()=>crypto.randomUUID())};}
   if(op==='mine')return {ok:true,submissions:[{id:'pending-demo',title:'My build',status:'pending'}]};
   if(op==='status')return {ok:true,id:'pending-demo',status:'pending',digest:'test',folder};
   throw Error('Unexpected operation '+op);
  };
  (window.MsbtWorkspace?.enabled ? window.MsbtWorkspace.open('serial-tools','saved') : switchTab('serial-tools'));$('communityOpenBtn').click();await idle();
  check($('communityFoldersPanel').open && !$('communityFoldersPanel').hidden,'community panel opens');check($('savedItemsLocalPanel').hidden,'local items hidden while browsing');$('savedItemsLocalBtn').click();check(!$('savedItemsLocalPanel').hidden && $('communityFoldersPanel').hidden,'local navigation');$('savedItemsShareBtn').click();check($('communitySubmitPanel').open && !$('communityFoldersPanel').hidden,'share shortcut');$('communityOpenBtn').click();await idle();check($('communityResults').textContent.includes('Vex starter'),'public results');
  $('communityResults').querySelector('button').click();await idle();
  check(!$('communityImportBtn').disabled,'approved import enabled');check(!$('communityPreviewItems').querySelector('img'),'untrusted title rendered as text');check(!imported,'preview never imports');
  const boxes=$('communityPreviewItems').querySelectorAll('input[type=checkbox]');
  boxes[0].click();check(savedDeliveryEntries().length===1,'single community selection');
  boxes[1].click();check(savedDeliveryEntries().length===2,'multiple community selection');
  $('communityClearSelection').click();check(savedDeliveryEntries().length===0,'clear community selection');
  $('communitySelectAll').click();check(savedDeliveryEntries().length===2,'all community entries including duplicate codes');
  check(getComputedStyle($('savedItemsDelivery')).display!=='none' && !$('savedItemsLocalPanel').contains($('savedItemsDelivery')),'delivery visible outside hidden local view');
  check(!$('savedSendBtn').disabled,'send enabled with community selection');
  folder.items.push(...Array.from({length:101},()=>({name:'More',folder:'',serial:'@UAbCd'})));
  $('communitySelectAll').click();check(savedDeliveryEntries().length===103,'select all includes unrendered items');
  folder.items.splice(2);$('communityClearSelection').click();check($('savedSendBtn').disabled,'send disabled with no selection');$('communitySelectAll').click();
  const originalSend=sendSerialPayload, originalConfirm=window.confirm, originalValidator=serialValidationMessage;
  let delivery;
  sendSerialPayload=async(...args)=>{delivery=args;return {ok:true,message:'Test only'};};
  window.confirm=()=>true;serialValidationMessage=()=>'';
  $('bookmarkOverrideLevel').checked=true;$('bookmarkOverrideLevel').dispatchEvent(new Event('change'));$('bookmarkDeliveryLevel').value='35';
  $('savedSendBtn').click();await new Promise(r=>setTimeout(r,10));
  check(delivery[1]==='@UAbCd\\n@UAbCd','community preserves duplicates');
  check(delivery[2]===true&&delivery[3]===35,'community relevel forwarded');
  $('savedItemsLocalBtn').click();openBookmarkFolder('Mine');selectAllVisibleBookmarks();
  await sendBookmarkSerial('local');check(delivery[1]==='@UKeep','local uses local selection');
  check(quickMenuBookmarkSerialPayload().serial_level===35,'quick menu relevel forwarded');
  sendSerialPayload=originalSend;window.confirm=originalConfirm;serialValidationMessage=originalValidator;
  $('communityOpenBtn').click();await idle();$('communityResults').querySelector('button').click();await idle();
  check(savedDeliveryEntries().length===0,'opening folder resets online selection');
  $('communityImportBtn').click();await idle();check(imported,'explicit import');check(state.bookmarks.length===5,'append preserves original');check(state.bookmarks[0].serial==='@UKeep','original unchanged');
  $('communitySubmitFolder').value='Builds / Vex';$('communitySubmitFolder').dispatchEvent(new Event('change'));
  $('communitySubmitTitle').value='My build';$('communitySubmitCreator').value='Tester';
  $('communitySubmitBtn').click();await idle();check(!sent,'consent required');
  $('communitySubmitConsent').checked=true;$('communitySubmitBtn').click();await idle();
  check(sent.items.length===2,'selected subtree only');check(sent.items[0].serial===sent.items[1].serial,'duplicates preserved');check(sent.items[1].folder==='Shields','subfolder preserved');check(!JSON.stringify(sent).includes('@UKeep'),'unselected bookmark not sent');
  $('communityMineBtn').click();await idle();$('communityResults').querySelector('button').click();await idle();check($('communityImportBtn').disabled,'pending cannot import');check($('communityCopyBtn').disabled,'pending has no public share');
  check(!calls.some(x=>/boost|deliver|afk/.test(x)),'no game actions');
  // Both sources use the exact Inventory renderer; cached resolution must preserve codes.
  savedCardCache.set('@UAbCd', {meta_ok:true,display_name:'Resolved test shield',item_type:'Shield',level:70,rarity:'Legendary'});
  $('savedItemsLocalBtn').click();openBookmarkFolder('Builds / Vex');
  check($('bookmarkRows').querySelectorAll('.saved-item-card.bl4-item-card').length===2,'local inventory cards');
  check(state.bookmarks.find(x=>x.id==='a').serial==='@UAbCd','card rendering preserves serial');
  const afkBrowse=document.getElementById('afkBookmarkFolder').nextElementSibling;
  afkBrowse.click();await idle();check(state.activeTab==='serial-tools','AFK shortcut targets the real saved-items tab');
  $('communitySearchBtn').click();await idle();$('communityResults').querySelector('button').click();await idle();
  check($('communityPreviewItems').querySelectorAll('.saved-item-card.bl4-item-card').length===2,'community inventory cards');
  $('communityFoldersPanel').scrollIntoView({block:'start'});
  return {operations:calls.length,bookmarks:state.bookmarks.length};
 })()`);
 assert.equal(result.bookmarks,5);
 win.showInactive();
 await new Promise(resolve=>setTimeout(resolve,500));
 await win.webContents.executeJavaScript(`(async()=>{await endWalkthrough({skipped:true,quiet:true});(window.MsbtWorkspace?.enabled ? window.MsbtWorkspace.open('serial-tools','saved') : switchTab('serial-tools'));document.querySelector('[data-msbt-panel="serial-bookmarks"]').scrollIntoView({block:'start'});})()`);
 await new Promise(resolve=>setTimeout(resolve,250));
 const out=path.join(__dirname,'..','output','community-folders-review');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'community-folders.png'),(await win.webContents.capturePage()).toPNG());
 await win.webContents.executeJavaScript(`document.getElementById('savedItemsLocalBtn').click();document.querySelector('[data-msbt-panel="serial-bookmarks"]').scrollIntoView({block:'start'});`);
 await new Promise(resolve=>setTimeout(resolve,200));
 const rendered=await win.webContents.executeJavaScript(`document.querySelectorAll('#bookmarkRows iframe[data-rendered="true"]').length`);assert.equal(rendered,2,'native cards actually render');
 fs.writeFileSync(path.join(out,'saved-items.png'),(await win.webContents.capturePage()).toPNG());
 console.log('PASS community UI: consent, selected subtree, safe preview, pending privacy, append-only import, no game actions');win.destroy();app.exit(0);
}).catch(e=>{console.error(e);app.exit(1)});
