"use strict";
const assert = require("assert");
const path = require("path");
const fs = require("fs");
const { app, BrowserWindow } = require("electron");
app.disableHardwareAcceleration();
app.whenReady().then(async () => {
  const win = new BrowserWindow({ show: false, width: 1300, height: 1000, webPreferences: { sandbox: false, partition: `afk-${process.pid}` } });
  await win.loadFile(path.join(__dirname, "renderer.html"), { query: { nosplash: "1" } });
  const results = await win.webContents.executeJavaScript(`(async () => {
    const calls = [];
    window.msbt = window.msbt || {};
    window.msbt.loadSerialBookmarks = async () => ({ok:true,data:{bookmarks:[{name:"Test bookmark",group:"Test",serial:"@Ufixture"}]}});
    bridgeAction = async (action,payload) => {
      calls.push({action,payload});
      return {ok:true,data:{ok:true,afk_lobby:{enabled:action==='afk_lobby_start',message:action==='afk_lobby_start'?'Running':'Stopped',config:payload,history:[]}}};
    };
    bridgeStatus = async () => {};
    window.msbtAfkRender({afk_lobby:{enabled:false,message:'Stopped',history:[],shift_connected:true,shift_running:false}});
    document.getElementById('afkLoadBookmarks').click();
    await new Promise(resolve=>setTimeout(resolve,30));
    document.getElementById('afkBookmarks').options[0].selected = true;
    document.getElementById('afkAddBookmarks').click();
    const codes = document.getElementById('afkCodes').value;
    state.bl4Entries = [{id:'a',serial:'@UCatalogAlpha',name:'Alpha'},{id:'b',serial:'@UCatalogBeta',name:'Beta'}];
    state.bl4SelectedIds = new Set(['a','b']);
    state.bl4ActiveId = 'a';
    document.getElementById('bl4AddToAfkBtn').click();
    document.getElementById('bl4AddThisToAfkBtn').click();
    const catalogCodes = document.getElementById('afkCodes').value;
    const savedCodes = JSON.parse(localStorage.getItem('msbt.afk-lobby.v1')).codes;
    const kickDefaultOff = !document.getElementById('afkAutoKick').checked;
    document.getElementById('afkAutoKick').checked = true;
    document.getElementById('afkStart').click();
    await new Promise(resolve=>setTimeout(resolve,30));
    const locked = document.getElementById('afkCodes').disabled;
    const stopEnabled = !document.getElementById('afkStop').disabled;
    document.getElementById('bl4AddToAfkBtn').click();
    const unchangedWhileRunning = document.getElementById('afkCodes').value === catalogCodes;
    document.getElementById('afkStop').click();
    await new Promise(resolve=>setTimeout(resolve,30));
    const unlocked = !document.getElementById('afkCodes').disabled;
    window.msbtAfkRender({afk_lobby:{enabled:false,message:'Ready for testing — select boosts, then Start AFK Lobby.',history:[],shift_connected:true,shift_running:false}});
    const panel = document.getElementById('afkLobbyPanel');
    document.querySelector('[data-workspace-local-section="afk"]').click();
    document.getElementById('msbtBootSplash').style.display = 'none';
    if (getComputedStyle(panel).display === 'none') throw new Error('AFK navigation did not reveal panel');
    panel.scrollIntoView();
    document.getElementById('afkCloseShift').click();
    await new Promise(resolve => setTimeout(resolve, 20));
    return {calls,codes,catalogCodes,savedCodes,kickDefaultOff,unchangedWhileRunning,locked,unlocked,stopEnabled,hasSduLabel:panel.textContent.includes('3,225')};
  })()`);
  assert.equal(results.codes, "@Ufixture");
  assert.equal(results.catalogCodes, "@Ufixture\n@UCatalogAlpha\n@UCatalogBeta\n@UCatalogAlpha");
  assert.equal(results.savedCodes, results.catalogCodes);
  assert(results.unchangedWhileRunning);
  assert.equal(results.calls[0].action, "afk_lobby_start");
  assert.equal(results.calls[0].payload.sdu, true);
  assert.equal(results.calls[0].payload.loot, true);
  assert.equal(results.calls[0].payload.auto_accept, true);
  assert(results.kickDefaultOff);
  assert.equal(results.calls[0].payload.auto_kick, true);
  assert.equal(results.calls[1].action, "afk_lobby_stop");
  assert.equal(results.calls[2].action, "shift_overlay_control");
  assert.equal(results.calls[2].payload.mode, "close");
  assert(results.locked && results.unlocked && results.stopEnabled && results.hasSduLabel);
  const out = path.join(__dirname, "../output/afk-lobby");
  fs.mkdirSync(out, { recursive: true });
  win.show();
  await new Promise(resolve => setTimeout(resolve, 600));
  await win.webContents.executeJavaScript(`document.getElementById('walkthroughModal')?.remove(); document.getElementById('walkthroughCard')?.remove(); document.getElementById('msbtBootSplash')?.remove(); document.getElementById('afkLobbyPanel').scrollIntoView();`);
  await new Promise(resolve => setTimeout(resolve, 200));
  fs.writeFileSync(path.join(out, "panel.png"), (await win.webContents.capturePage()).toPNG());
  console.log("PASS AFK UI: bookmarks, start payload, fixed SDU control, edit lock, stop, screenshot.");
  win.destroy(); app.exit(0);
}).catch(error => { console.error(error); app.exit(1); });
