"use strict";
const assert = require("node:assert/strict"), path = require("node:path");
const {app, BrowserWindow, protocol, session} = require("electron");
const nativeProtocol = require("./native_card_protocol");
nativeProtocol.registerNativeCardSchemes(protocol);
app.whenReady().then(async () => {
  const partition = `inventory-selection-${process.pid}`;
  nativeProtocol.installNativeCardProtocol(session.fromPartition(partition).protocol);
  const win = new BrowserWindow({show:false,width:1100,height:800,webPreferences:{partition,sandbox:true,backgroundThrottling:false}});
  try {
    await win.loadFile(path.join(__dirname,"renderer.html"),{query:{nosplash:"1"}});
    const result = await win.webContents.executeJavaScript(`(async()=>{
      const check=(ok,message)=>{if(!ok)throw new Error(message);};
      const wait=()=>new Promise(resolve=>setTimeout(resolve,50));
      const item={serial:'@UsameCaseSensitiveSerial',display_name:'Selection fixture',item_type:'Pistol',rarity:'Legendary',level:60,damage:100};
      state.invEquipped=[{...item,origin:'equipped',slot:0}];
      state.invBackpack=Array.from({length:5},(_,i)=>({...item,origin:'backpack',backpack_index:i}));
      state.invSelectedKeys=new Set();state.invSelectionAnchor='';state.invMultiSelect=false;
      state.invPage=0;state.invPageSize=3;state.invFiltered=state.invBackpack.slice();
      const scroll=document.createElement('div');scroll.style.cssText='height:650px;overflow:auto;width:1000px';
      [els.invEquippedGrid,els.invBackpackGrid].forEach(grid=>grid.style.gridTemplateColumns='repeat(2,minmax(0,1fr))');
      document.querySelectorAll('dialog[open]').forEach(dialog=>dialog.close());
      scroll.append(els.invEquippedGrid,els.invBackpackGrid,els.invDetail);
      document.body.replaceChildren(scroll);
      invRenderEquipped();invRenderBackpack();
      const tiles=[...scroll.querySelectorAll('[data-inv-key]')],frames=[...scroll.querySelectorAll('iframe')];
      frames.forEach(frame=>frame.loading='eager');
      const deadline=Date.now()+10000;
      while(frames.some(frame=>frame.dataset.rendered!=='true')&&Date.now()<deadline)await wait();
      check(frames.every(frame=>frame.dataset.rendered==='true'),'native frames did not finish loading');
      // The rendered notification precedes the final asynchronous fitted size.
      await new Promise(resolve=>setTimeout(resolve,200));
      const windows=frames.map(frame=>frame.contentWindow),heights=frames.map(frame=>frame.style.height);
      let mutations=0,loads=0;
      const observer=new MutationObserver(rows=>{mutations+=rows.length;});
      [els.invEquippedGrid,els.invBackpackGrid].forEach(grid=>observer.observe(grid,{childList:true,subtree:true}));
      frames.forEach(frame=>frame.addEventListener('load',()=>loads++));
      const backpack=[...els.invBackpackGrid.children];
      scroll.scrollTop=120;const top=scroll.scrollTop;check(top>0,'test inventory must be scrollable');
      backpack[0].focus({preventScroll:true});backpack[0].click();
      check(document.activeElement===backpack[0],'selection lost keyboard focus');
      check(state.invSelectedKeys.size===1 && backpack[0].classList.contains('selected'),'single selection failed');
      check(backpack[0].getAttribute('aria-pressed')==='true','accessible selection state missing');
      check(!backpack[1].classList.contains('selected'),'identical serials at different positions were conflated');
      check(els.invDetailSerial.value===item.serial,'selected serial detail changed');
      backpack[1].dispatchEvent(new MouseEvent('click',{ctrlKey:true,bubbles:true}));
      check(state.invSelectedKeys.size===2,'Ctrl selection failed');
      backpack[2].dispatchEvent(new MouseEvent('click',{shiftKey:true,bubbles:true}));
      check(backpack[1].classList.contains('selected')&&backpack[2].classList.contains('selected'),'Shift range failed');
      els.invMultiSelectToggle.checked=true;els.invMultiSelectToggle.dispatchEvent(new Event('change'));
      const beforeToggle=state.invSelectedKeys.size;backpack[2].click();
      check(state.invSelectedKeys.size===beforeToggle-1,'multi-select toggle failed');
      invSelectAllFiltered();
      check(state.invSelectedKeys.size===5,'select-all must include other pages');
      check(els.invSelectedCount.textContent==='5 selected','selection count stale');
      check(els.invCopyAllBtn.textContent==='Copy Selected Serials','copy label stale');
      invClearDetail();check(els.invDetail.classList.contains('hidden'),'details did not close');
      check(state.invSelectedKeys.size===5,'closing details cleared selection');
      invClearSelection();
      check(state.invSelectedKeys.size===0 && !scroll.querySelector('.selected'),'clear selection failed');
      check(els.invSelectedCount.textContent==='0 selected','clear count stale');
      check(els.invCopyAllBtn.textContent==='Copy Visible Serials','clear copy label stale');
      const equipped=els.invEquippedGrid.querySelector('[data-inv-key]');equipped.click();
      check(equipped.classList.contains('selected')&&state.invSelectedKeys.size===1,'equipped selection failed');
      await wait();observer.disconnect();
      check(mutations===0,'selection rebuilt grid content');check(loads===0,'selection reloaded native frames');
      check(tiles.every(tile=>tile.isConnected),'selection replaced item tiles');
      check(frames.every((frame,i)=>frame.isConnected&&frame.contentWindow===windows[i]&&Math.abs(parseFloat(frame.style.height)-parseFloat(heights[i]))<=2),'selection replaced or collapsed native frames: '+JSON.stringify({before:heights,after:frames.map(frame=>frame.style.height)}));
      check(scroll.scrollTop===top,'selection moved inventory scroll position');
      // Paging still renders new data and restores selections by position key.
      invSelectAllFiltered();state.invPage=1;invRenderBackpack();
      check(els.invBackpackGrid.children.length===2,'paging failed');
      check([...els.invBackpackGrid.children].every(tile=>tile.classList.contains('selected')),'next page lost selected highlights');
      return {frames:frames.length,mutations,loads,scrollPreserved:true};
    })()`);
    assert.equal(result.mutations,0);assert.equal(result.loads,0);
    console.log("PASS Inventory selection: native frames, tile identity, focus and scroll preserved; single/Ctrl/Shift/multiple/all/clear/equipped/paging correct",JSON.stringify(result));
  } finally {win.destroy();}
  app.exit(0);
}).catch(error=>{console.error(error);app.exit(1);});
