'use strict';
const {app,BrowserWindow,protocol}=require('electron');
const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const native=require('./native_card_protocol');native.registerNativeCardSchemes(protocol);
app.on('window-all-closed',()=>{});
app.whenReady().then(async()=>{
 native.installNativeCardProtocol(protocol);
 const card=await require('./native_card_capture').captureNativeWidget(BrowserWindow,require('./fixtures/native_widgets/draupner.json'));
 const win=new BrowserWindow({show:false,width:1200,height:900,useContentSize:true,webPreferences:{offscreen:true,contextIsolation:true,nodeIntegration:false,partition:'preview-test-'+process.pid}});
 await win.loadFile(path.join(__dirname,'renderer.html'),{query:{nosplash:'1'}});
 const result=await win.webContents.executeJavaScript(`(async()=>{
 const check=(v,m)=>{if(!v)throw Error(m)};
 const wait=async fn=>{for(let n=0;n<100;n++){if(fn())return;await new Promise(r=>setTimeout(r,20));}throw Error('Preview timed out');};
 let requests=0;
 window.msbt={itemCardImages:async()=>({items:[]}),nativeItemPreview:async()=>{requests++;return {ok:true,widget:{Name:'Zealous Regulated Draupner'},image:${JSON.stringify(card)}}}};
 document.body.replaceChildren();
 const host=document.createElement('div');host.style.cssText='width:240px;margin:25px';document.body.append(host);
 host.append(invMakeCard({serial:'@UPreview'}));await wait(()=>host.querySelector('.item-card-view-button'));
 const thumb=host.querySelector('img'),button=host.querySelector('.item-card-view-button');
 const br=button.getBoundingClientRect();
 check(document.elementFromPoint(br.left+br.width/2,br.top+br.height/2)===button,'inventory pointer hit must reach View card, not select the tile');
 check(getComputedStyle(thumb).pointerEvents==='auto','inventory hover target must receive pointer input');
 check(thumb.getBoundingClientRect().height<=280,'thumbnail must be cropped');
 thumb.dispatchEvent(new PointerEvent('pointerenter',{pointerType:'mouse'}));await wait(()=>document.querySelector('.item-card-popout'));
 let panel=document.querySelector('.item-card-popout'),scroll=panel.querySelector('.item-card-popout-scroll'),full=scroll.querySelector('img');
 await wait(()=>full.complete&&full.naturalHeight>0);
 check(panel.matches(':popover-open'),'preview must open above dialogs');
 check(full.getBoundingClientRect().width>thumb.getBoundingClientRect().width*2,'popout is readable at larger size');
 check(full.getBoundingClientRect().height>thumb.getBoundingClientRect().height,'full uncropped image');
 check(panel.dataset.previewMode==='hover'&&panel.inert&&getComputedStyle(panel).pointerEvents==='none','hover must not capture pointer or keyboard');
 const next=document.createElement('img');next.src=thumb.src;next.alt='Next item';next.style.cssText='position:fixed;left:'+panel.style.left+';top:'+panel.style.top+';width:200px;height:200px';document.body.append(next);
 const nr=next.getBoundingClientRect();check(document.elementFromPoint(nr.left+20,nr.top+20)===next,'hover popup must allow hitting the next item underneath');next.remove();
 button.click();panel=document.querySelector('.item-card-popout');scroll=panel.querySelector('.item-card-popout-scroll');full=scroll.querySelector('img');
 check(panel.dataset.previewMode==='pinned'&&!panel.inert,'View card promotes hover to interactive preview');
 const zoom=panel.querySelector('input');zoom.value='200';zoom.dispatchEvent(new Event('input'));
 check(scroll.scrollWidth>scroll.clientWidth,'zoom supports horizontal scrolling');
 scroll.scrollTop=scroll.scrollHeight;check(scroll.scrollTop>0,'long cards scroll to footer');
 document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));check(!document.querySelector('.item-card-popout'),'Escape dismisses');
 button.click();await wait(()=>document.querySelector('.item-card-popout'));
 document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));check(document.activeElement===button,'keyboard focus restored');
 button.click();await wait(()=>document.querySelector('.item-card-popout'));
 check(requests===1,'hover and zoom never regenerate a card');
 return {cropped:true,hover:true,hitThrough:true,pinned:true,zoom:true,scroll:true,keyboard:true,requests};
 })()`);
 assert.equal(result.requests,1);
 win.webContents.invalidate();await new Promise(r=>setTimeout(r,100));
 fs.mkdirSync(path.resolve(__dirname,'../output/card-layout'),{recursive:true});
 fs.writeFileSync(path.resolve(__dirname,'../output/card-layout/hover-preview.png'),(await win.webContents.capturePage()).toPNG());
 win.setContentSize(360,600);await new Promise(r=>setTimeout(r,100));
 const narrow=await win.webContents.executeJavaScript(`(()=>{document.querySelector('.item-card-view-button').click();const r=document.querySelector('.item-card-popout').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight;})()`);
 assert.equal(narrow,true,'preview must stay inside narrow viewport');
 const recycled=await win.webContents.executeJavaScript(`(async()=>{document.body.replaceChildren();await new Promise(r=>setTimeout(r,50));return !document.querySelector('.item-card-popout');})()`);
 assert.equal(recycled,true);console.log(JSON.stringify({...result,recycled,narrow}));win.destroy();app.exit(0);
}).catch(e=>{console.error(e);app.exit(1)});
