const assert = require('assert/strict');
const fs = require('fs/promises');
const os = require('os');
const path = require('path');
const {app, BrowserWindow} = require('electron');
const store = require('./serial_bookmarks_store');
app.disableHardwareAcceleration();
app.whenReady().then(async()=>{
  const dir = await fs.mkdtemp(path.join(os.tmpdir(),'msbt-folders-'));
  const file = path.join(dir,'serial_bookmarks.json');
  const rows = [{id:'a',name:'Same',group:'Old group',serial:'@Uone'}, {id:'b',name:'Same',group:'Old group',serial:'@Uone'}];
  const saved = await store.writeBookmarks(file,{bookmarks:rows,folders:['Empty / Nested']});
  assert.equal(saved.data.bookmarks.length,2);
  await store.writeBookmarks(file,{bookmarks:saved.data.bookmarks});
  assert.ok((await store.readBookmarks(file)).data.folders.includes('Empty / Nested'));
  const win = new BrowserWindow({show:false,webPreferences:{sandbox:false,partition:'folder-test-'+process.pid}});
  await win.loadFile(path.join(__dirname,'renderer.html'),{query:{nosplash:'1'}});
  const result = await win.webContents.executeJavaScript(`(async()=>{
    const check=(value,message)=>{if(!value)throw Error(message)};
    let persisted;
    window.msbt=window.msbt||{};
    window.msbt.saveSerialBookmarks=async data=>{persisted=JSON.parse(JSON.stringify(data));return {ok:true,data:persisted}};
    state.bookmarks=[{id:'a',name:'Gun',group:'Weapons / Shotguns',serial:'@Uone'},{id:'b',name:'Shield',group:'Shields',serial:'@Utwo'}];
    state.bookmarkFolders=['Empty / Child'];state.bookmarkCheckedIds=new Set(['a']);renderBookmarks();
    els.bookmarkGroupFilter.value='Weapons';renderBookmarks();
    check(state.bookmarkVisibleRows.length===1,'parent should include child items');
    document.getElementById('bookmarkNewFolderPath').value='Builds / Vex / Starter';
    await manageBookmarkFolder(false);
    check(document.getElementById('bookmarkFolderPath').tagName==='SELECT','existing folders use dropdown');
    document.getElementById('bookmarkFolderPath').value='Builds / Vex / Starter';
    await manageBookmarkFolder(true);
    check(persisted.bookmarks[0].group==='Builds / Vex / Starter','move');
    check(persisted.bookmarks[0].serial==='@Uone'&&persisted.bookmarks[1].group==='Shields','preserve unrelated bookmarks');
    check(bookmarkGroups().includes('Builds / Vex'),'ancestor');
    document.getElementById('bookmarkNewFolderPath').value='Another / Empty';await manageBookmarkFolder(false);
    check(persisted.folders.includes('Another / Empty'),'empty folder saved');
    check([...els.bookmarkGroup.options].some(o=>o.value==='Another / Empty'),'new folder available as save destination');
    els.bookmarkGroup.value='Another / Empty';renderBookmarks();check(els.bookmarkGroup.value==='Another / Empty','preserve chosen save destination');
    window.confirm=()=>true;
    window.msbt.loadSerialBookmarks=async()=>({ok:true,data:{bookmarks:state.bookmarks,folders:state.bookmarkFolders}});
    await bookmarksForTest();
    async function bookmarksForTest() {
      document.getElementById('afkLoadBookmarks').click();
      await new Promise(resolve=>setTimeout(resolve,20));
    }
    const afkFolder=document.getElementById('afkBookmarkFolder');
    afkFolder.value='Builds';afkFolder.dispatchEvent(new Event('change'));
    check(document.getElementById('afkBookmarks').options.length===1,'AFK parent folder browse');
    document.getElementById('afkGuaranteedCodes').value='';
    document.getElementById('afkAddGuaranteedFolder').click();
    check(document.getElementById('afkGuaranteedCodes').value==='@Uone','AFK add folder guaranteed');
    els.bookmarkGroupFilter.value='Builds';
    await deleteBookmark(true);
    check(state.bookmarks.length===1&&state.bookmarks[0].id==='b','folder deletes descendants only');
    check(!state.bookmarkFolders.some(f=>f.startsWith('Builds')),'descendant folders deleted');
    check(document.getElementById('afkGuaranteedCodes').value==='@Uone','deletion preserves AFK copy');
    state.bookmarks.push({id:'c',name:'Copy',group:'Shields',serial:'@Utwo'});
    state.bookmarkCheckedIds=new Set(['b','c']);
    window.confirm=()=>false;await deleteBookmark();check(state.bookmarks.length===2,'cancel deletion');
    window.confirm=()=>true;await deleteBookmark();check(state.bookmarks.length===0,'bulk deletes IDs including duplicate serials');
    els.bookmarkGroupFilter.value='Another';await deleteBookmark(true);
    check(!state.bookmarkFolders.includes('Another / Empty'),'delete empty folder tree');
    state.bookmarks=[{id:'b',name:'Shield',group:'Shields',serial:'@Utwo'}];
    state.bookmarkCheckedIds=new Set(['b']);renderBookmarks();
    const before=JSON.stringify(state.bookmarks);
    window.msbt.saveSerialBookmarks=async()=>({ok:false,message:'Disk failure'});
    document.getElementById('bookmarkNewFolderPath').value='Failed';await manageBookmarkFolder(false);
    check(JSON.stringify(state.bookmarks)===before&&!state.bookmarkFolders.includes('Failed'),'failed save rollback');
    await deleteBookmark();check(JSON.stringify(state.bookmarks)===before,'failed delete rollback');
    return true;
  })()`);
  assert.ok(result);win.destroy();console.log('PASS nested folders, parent filtering, empty-folder persistence, migration, move and rollback');app.exit(0);
}).catch(error=>{console.error(error);app.exit(1)});
