const {app,BrowserWindow,protocol}=require('electron');
const {registerNativeCardSchemes,installNativeCardProtocol}=require('./native_card_protocol');
registerNativeCardSchemes(protocol);
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
app.disableHardwareAcceleration();
app.whenReady().then(async()=>{
 const win=new BrowserWindow({width:1400,height:1000,show:false,webPreferences:{partition:'community-ui-'+process.pid}});
 installNativeCardProtocol(win.webContents.session.protocol);
 await win.loadFile(path.join(__dirname,'renderer.html'),{query:{nosplash:'1'}});
 const result=await win.webContents.executeJavaScript(`(async()=>{
  const check=(v,m)=>{if(!v)throw Error(m)},$=id=>document.getElementById(id);
  await runBootSplash();
  const idle=async()=>{for(let i=0;i<100&&$('communityFoldersPanel').getAttribute('aria-busy')==='true';i++)await new Promise(r=>setTimeout(r,10));};
  state.bookmarks=[{id:'old',name:'Keep me',serial:'@UKeep',group:'Mine'},{id:'a',name:'A',serial:'@UAbCd',group:'Builds / Vex'},{id:'b',name:'B',serial:'@UAbCd',group:'Builds / Vex / Shields'}];state.bookmarkFolders=['Mine','Builds / Vex','Builds / Vex / Shields'];renderBookmarks();
  $('bookmarkGroupFilter').value='Mine';$('bookmarkGroupFilter').dispatchEvent(new Event('change'));
  check($('bookmarkRows').querySelectorAll('.bookmark-row').length===1,'folder dropdown filters Mine');
  state.bookmarkCheckedIds.add('old');state.bookmarkActiveId='old';
  $('bookmarkGroupFilter').value='Builds / Vex';$('bookmarkGroupFilter').dispatchEvent(new Event('change'));
  check($('bookmarkRows').querySelectorAll('.bookmark-row').length===2,'folder shows subtree');
  check(bookmarkSelectedEntries().length===0,'switch clears old folder selection');
  $('bookmarkSelectAllBtn').click();check(bookmarkSelectedEntries().length===2,'select all local');
  $('bookmarkClearSelectedBtn').click();check(bookmarkSelectedEntries().length===0,'clear means no delivery');
  let sent,imported=false,presentations=[],calls=[],queries=[],releaseSearch=null,delaySearch=false,paginated=false,failPage=false,pageRequests=[];
  const folder={version:1,title:'Vex starter',creator:'Community tester',description:'Gun and shield drop list',folders:['','Shields'],items:[{name:'<img src=x onerror=alert(1)>',folder:'',serial:'@UAbCd'},{name:'Shield',folder:'Shields',serial:'@UAbCd'}]};
  window.msbt=window.msbt||{};
  window.msbt.itemCardImages=async()=>({items:[]});
  window.msbt.nativeItemPreview=async serial=>({ok:true,widget:{Name:'Native fixture'},image:{ok:true,base64:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6LksAAAAASUVORK5CYII='}});
  window.msbt.communityFolders=async(op,p)=>{calls.push(op);
   if(op==='info')return {ok:true,endpoint:'https://library.example'};
   if(op==='list'){
    queries.push(p.q);
    pageRequests.push({...p});
    if(failPage){failPage=false;return {ok:false,message:'Page unavailable'};}
    if(delaySearch){delaySearch=false;await new Promise(resolve=>{releaseSearch=resolve;});}
    if(paginated)return {ok:true,next:p.offset===0?25:p.offset===25?50:null,folders:[{id:'page-'+p.offset,title:'Page at '+p.offset,status:'approved'}]};
    const match=!p.q||[folder.title,folder.creator].some(x=>x.toLowerCase().includes(p.q.toLowerCase()));
    return {ok:true,next:null,folders:match?[{id:'demo',title:folder.title,creator:folder.creator,item_count:2,status:'approved'}]:[]};
   }
   if(op==='get')return {ok:true,id:'demo',status:'approved',digest:'test',folder,presentations};
   if(op==='submit'){sent=p.folder;return {ok:true,status:'pending',id:'pending-demo'};}
   if(op==='import'){imported=true;return {ok:true,imported:2,destination:'Vex starter',data:window.communityFolderContract.importFolder(folder,{bookmarks:state.bookmarks,folders:state.bookmarkFolders},()=>crypto.randomUUID())};}
   if(op==='mine')return {ok:true,submissions:[{id:'pending-demo',title:'My build',status:'pending'}]};
   if(op==='status')return {ok:true,id:'pending-demo',status:'pending',digest:'test',folder};
   throw Error('Unexpected operation '+op);
  };
  (window.MsbtWorkspace?.enabled ? window.MsbtWorkspace.open('serial-tools','saved') : switchTab('serial-tools'));$('communityOpenBtn').click();await idle();
  check($('communityFoldersPanel').open && !$('communityFoldersPanel').hidden,'community panel opens');check($('savedItemsLocalPanel').hidden,'local items hidden while browsing');$('savedItemsLocalBtn').click();check(!$('savedItemsLocalPanel').hidden && $('communityFoldersPanel').hidden,'local navigation');$('savedItemsShareBtn').click();check($('communitySubmitPanel').open && !$('communityFoldersPanel').hidden,'share shortcut');$('communityOpenBtn').click();await idle();check($('communityResults').textContent.includes('Vex starter'),'public results');
  $('communitySearch').value='  Vex  ';$('communitySearch').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await idle();
  check(queries.at(-1)==='Vex'&&$('communityResults').textContent.includes('Vex starter'),'Enter searches and trims spaces');
  $('communitySearch').value='missing';$('communitySearch').dispatchEvent(new Event('input'));await new Promise(r=>setTimeout(r,300));await idle();
  check($('communityResults').textContent==='No folders found.','typing filters results');
  delaySearch=true;$('communitySearch').value='old';$('communitySearchBtn').click();
  $('communitySearch').value='Community tester';$('communitySearchBtn').click();
  releaseSearch();await idle();
  check(queries.at(-1)==='Community tester'&&$('communityResults').textContent.includes('Vex starter'),'search during loading is retained');
  $('communitySearch').value='';$('communitySearch').dispatchEvent(new Event('input'));await new Promise(r=>setTimeout(r,300));await idle();
  check(queries.at(-1)===''&&$('communityResults').querySelector('button'),'clearing search restores folders');
  paginated=true;$('communitySearch').value='Vex';$('communitySearchBtn').click();await idle();
  check(!$('communityPagination').hidden&&$('communityPreviousBtn').disabled&&!$('communityMoreBtn').disabled,'first page navigation');
  $('communityMoreBtn').click();await idle();$('communityMoreBtn').click();await idle();
  check(pageRequests.at(-1).offset===50&&$('communityMoreBtn').disabled&&!$('communityPreviousBtn').disabled,'last page navigation');
  $('communitySearch').value='unsubmitted';
  failPage=true;$('communityPreviousBtn').click();await idle();
  check($('communityResults').textContent.includes('Page at 50'),'failed page retains current results');
  $('communityPreviousBtn').click();await idle();
  check(pageRequests.at(-1).offset===25&&pageRequests.at(-1).q==='Vex','previous retries correct page with active query');
  $('communityPreviousBtn').click();await idle();
  check(pageRequests.at(-1).offset===0&&pageRequests.at(-1).q==='Vex'&&$('communityPreviousBtn').disabled,'previous reaches first page without changing search');
  $('communityMoreBtn').click();await idle();$('communitySearch').value='new';$('communitySearchBtn').click();await idle();
  check(pageRequests.at(-1).offset===0&&$('communityPreviousBtn').disabled,'new search resets pagination');
  $('communityMoreBtn').click();await idle();$('communityMineBtn').click();await idle();
  check($('communityPagination').hidden,'submissions hide pagination');
  paginated=false;$('communitySearch').value='';$('communitySearchBtn').click();await idle();
  check($('communityPagination').hidden,'single page hides pagination');
  $('communityResults').querySelector('button').click();await idle();
  check(!$('communityPreviewNotes').hidden && $('communityPreviewNotes').open,'folder notes visible on selection');
  check($('communityPreviewDescription').textContent===folder.description,'public description appears as notes');
  check(getComputedStyle($('communityPreviewDescription')).whiteSpace==='pre-wrap','notes retain line breaks');
  check($('communityPreviewCreator').textContent.includes(folder.creator),'creator separate from notes');
  check(!$('communityImportBtn').disabled,'approved import enabled');check(!$('communityPreviewItems').querySelector('img'),'untrusted title rendered as text');check(!imported,'preview never imports');
  const boxes=$('communityPreviewItems').querySelectorAll('input[type=checkbox]');
  boxes[0].click();check(savedDeliveryEntries().length===1,'single community selection');
  boxes[1].click();check(savedDeliveryEntries().length===2,'multiple community selection');
  $('communityClearSelection').click();check(savedDeliveryEntries().length===0,'clear community selection');
  $('communitySelectAll').click();check(savedDeliveryEntries().length===2,'all community entries including duplicate codes');
  check(getComputedStyle($('savedItemsDelivery')).display!=='none' && !$('savedItemsLocalPanel').contains($('savedItemsDelivery')),'delivery visible outside hidden local view');
  check(!$('savedSendBtn').disabled,'send enabled with community selection');
  folder.items.push(...Array.from({length:101},()=>({name:'More',folder:'',serial:'@UAbCd'})));
  $('communitySelectAll').click();check(savedDeliveryEntries().length===103,'select all includes unrendered items');
  folder.items.splice(2);$('communityClearSelection').click();check($('savedSendBtn').disabled,'send disabled with no selection');$('communitySelectAll').click();
  const originalSend=sendSerialPayload, originalConfirm=window.confirm, originalValidator=serialValidationMessage;
  let delivery;
  sendSerialPayload=async(...args)=>{delivery=args;return {ok:true,message:'Test only'};};
  window.confirm=()=>true;serialValidationMessage=()=>'';
  $('bookmarkOverrideLevel').checked=true;$('bookmarkOverrideLevel').dispatchEvent(new Event('change'));$('bookmarkDeliveryLevel').value='35';
  $('savedSendBtn').click();await new Promise(r=>setTimeout(r,10));
  check(delivery[1]==='@UAbCd\\n@UAbCd','community preserves duplicates');
  check(delivery[2]===true&&delivery[3]===35,'community relevel forwarded');
  $('savedItemsLocalBtn').click();openBookmarkFolder('Mine');selectAllVisibleBookmarks();
  await sendBookmarkSerial('local');check(delivery[1]==='@UKeep','local uses local selection');
  check(quickMenuBookmarkSerialPayload().serial_level===35,'quick menu relevel forwarded');
  sendSerialPayload=originalSend;window.confirm=originalConfirm;serialValidationMessage=originalValidator;
  $('communityOpenBtn').click();await idle();$('communityResults').querySelector('button').click();await idle();
  check(savedDeliveryEntries().length===0,'opening folder resets online selection');
  $('communityImportBtn').click();await idle();check(imported,'explicit import');check(state.bookmarks.length===5,'append preserves original');check(state.bookmarks[0].serial==='@UKeep','original unchanged');
  $('communitySubmitFolder').value='Builds / Vex';$('communitySubmitFolder').dispatchEvent(new Event('change'));
  $('communitySubmitTitle').value='My build';$('communitySubmitCreator').value='Tester';
  $('communitySubmitBtn').click();await idle();check(!sent,'consent required');
  $('communitySubmitConsent').checked=true;$('communitySubmitBtn').click();await idle();
  check(sent.items.length===2,'selected subtree only');check(sent.items[0].serial===sent.items[1].serial,'duplicates preserved');check(sent.items[1].folder==='Shields','subfolder preserved');check(!JSON.stringify(sent).includes('@UKeep'),'unselected bookmark not sent');
  $('communityMineBtn').click();await idle();$('communityResults').querySelector('button').click();await idle();check($('communityImportBtn').disabled,'pending cannot import');check($('communityCopyBtn').disabled,'pending has no public share');
  check(!calls.some(x=>/boost|deliver|afk/.test(x)),'no game actions');
  // Local and Community folders both attach lazy shared card views.
  $('savedItemsLocalBtn').click();openBookmarkFolder('Builds / Vex');
  check($('bookmarkRows').querySelectorAll('.saved-item-card').length===2,'local inventory cards');
  check(state.bookmarks.find(x=>x.id==='a').serial==='@UAbCd','card rendering preserves serial');
  const afkIdle=async()=>{for(let i=0;i<100&&$('afkCommunityPicker').getAttribute('aria-busy')==='true';i++)await new Promise(r=>setTimeout(r,10));};
  const beforeTab=state.activeTab;
  $('afkCommunitySearchBtn').click();await afkIdle();
  check(state.activeTab===beforeTab,'AFK picker stays in place');
  $('afkCommunityFolder').selectedIndex=1;$('afkCommunityFolder').dispatchEvent(new Event('change'));
  $('afkCodes').value='@UKeep';$('afkGuaranteedCodes').value='';
  $('afkCommunityAdd').click();await afkIdle();
  check($('afkCodes').value==='@UKeep\\n@UAbCd\\n@UAbCd','AFK append preserves duplicates and existing codes');
  $('afkCommunityGuaranteed').click();await afkIdle();
  check($('afkGuaranteedCodes').value==='@UAbCd\\n@UAbCd','AFK guaranteed append');
  const prior=$('afkCodes').value;
  window.msbtAfkRender({afk_lobby:{enabled:true,config:{codes:prior}}});
  $('afkCommunityAdd').click();await afkIdle();
  check($('afkCodes').value===prior&&$('afkCommunityNote').textContent.includes('Stop AFK'),'running AFK blocks edits');
  window.msbtAfkRender({afk_lobby:{enabled:false}});
  const publicCall=window.msbt.communityFolders;
  window.msbt.communityFolders=async(op,p)=>op==='get'?{ok:true,status:'pending',folder}:publicCall(op,p);
  $('afkCommunityAdd').click();await afkIdle();
  check($('afkCodes').value===prior&&$('afkCommunityNote').textContent.includes('approved'),'pending folders blocked');
  window.msbt.communityFolders=publicCall;
  paginated=true;$('afkCommunitySearch').value=' Vex ';$('afkCommunitySearchBtn').click();await afkIdle();
  $('afkCommunityNext').click();await afkIdle();
  check(pageRequests.at(-1).offset===25&&pageRequests.at(-1).q==='Vex','AFK search pagination');
  $('afkCommunityPrevious').click();await afkIdle();check(pageRequests.at(-1).offset===0,'AFK previous page');
  paginated=false;$('communityOpenBtn').click();await idle();
  presentations=[{title:'GZO fixture title',title_source:'GZO exact code match',image_source:'GZO exact code match',image_url:'https://save-editor.be/GZO/fixture.png'},null];
  $('communitySearchBtn').click();await idle();$('communityResults').querySelector('button').click();await idle();
  check($('communityPreviewItems').querySelectorAll('.saved-item-card').length===2,'community shares lazy card loader');
  check($('communityPreviewItems').querySelector('.saved-item-card').cardItem.image_url==='https://save-editor.be/GZO/fixture.png','community passes supplied screenshot to shared loader');
  check($('communityPreviewItems').textContent.includes('GZO fixture title'),'GZO title shown');
  check($('communityPreviewItems').querySelectorAll('.saved-item-card')[1].cardItem.serial==='@UAbCd','unmatched item retains original serial for generation');
  $('communityFoldersPanel').scrollIntoView({block:'start'});
  return {operations:calls.length,bookmarks:state.bookmarks.length};
 })()`);
 assert.equal(result.bookmarks,5);
 console.log('PASS community pagination: next, previous, first/last page, failed request retry, query retention, search reset, submissions; search and folder selection/import/delivery wiring.');
 if(process.argv.includes('--functional-only')){win.destroy();app.exit(0);return;}
 win.showInactive();
 await new Promise(resolve=>setTimeout(resolve,500));
 await win.webContents.executeJavaScript(`(async()=>{await endWalkthrough({skipped:true,quiet:true});(window.MsbtWorkspace?.enabled ? window.MsbtWorkspace.open('serial-tools','saved') : switchTab('serial-tools'));document.querySelector('[data-msbt-panel="serial-bookmarks"]').scrollIntoView({block:'start'});})()`);
 await new Promise(resolve=>setTimeout(resolve,250));
 const out=path.join(__dirname,'..','output','community-folders-review');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'community-folders.png'),(await win.webContents.capturePage()).toPNG());
 await win.webContents.executeJavaScript(`document.getElementById('savedItemsLocalBtn').click();document.querySelector('[data-msbt-panel="serial-bookmarks"]').scrollIntoView({block:'start'});`);
 await new Promise(resolve=>setTimeout(resolve,200));
 const rendered=await win.webContents.executeJavaScript(`document.querySelectorAll('#bookmarkRows .saved-item-card img').length`);assert.equal(rendered,2,'shared cards actually render');
 fs.writeFileSync(path.join(out,'saved-items.png'),(await win.webContents.capturePage()).toPNG());
 const heights=[];
 for (const [width,height] of [[2560,1440],[1920,1080],[1280,720],[800,600],[480,800]]) {
  win.setContentSize(width,height);
  await new Promise(resolve=>setTimeout(resolve,80));
  const layout=await win.webContents.executeJavaScript(`({local:parseFloat(getComputedStyle(document.getElementById('bookmarkRows')).maxHeight),community:parseFloat(getComputedStyle(document.getElementById('communityPreviewItems')).maxHeight),width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth+2})`);
  assert.equal(layout.overflow,false,`Saved Items overflow at ${width}x${height}`);
  heights.push(layout);
 }
 assert.ok(heights[0].local>heights[1].local && heights[0].community>heights[1].community,'tall screens get taller lists');
 assert.ok(heights[3].local<=360,'small windows retain bounded scroll area');
 // A stalled embedded document must recover to a readable resolved card.
 await win.webContents.executeJavaScript(`{
  const host=document.createElement('div');host.id='stalledSavedCard';host.className='saved-item-card';document.body.append(host);
  fillBl4ItemCard(host,{meta_ok:true,display_name:'Recovered shield',item_type:'Shield',level:70,rarity:'Legendary'});
  const frame=host.querySelector('iframe');
  if(frame.loading!=='eager')throw Error('Saved cards must not add a second lazy-loading gate');
  frame.srcdoc='<html><body></body></html>';
 }`);
 await new Promise(resolve=>setTimeout(resolve,8500));
 const recovered=await win.webContents.executeJavaScript(`({frame:!!document.querySelector('#stalledSavedCard iframe'),text:document.getElementById('stalledSavedCard').textContent})`);
 assert.equal(recovered.frame,false,'stalled card replaced');
 assert.match(recovered.text,/Recovered shield/,'fallback includes resolved item name');
 console.log('PASS stalled imported card recovers to readable details');
 console.log('PASS adaptive Saved Items heights at 2560, 1920, 1280, 800 and 480 pixels');
 console.log('PASS community UI: consent, selected subtree, safe preview, pending privacy, append-only import, no game actions');win.destroy();app.exit(0);
}).catch(e=>{console.error(e);app.exit(1)});
