"use strict";
const {app,BrowserWindow}=require("electron");
const assert=require("node:assert/strict"),path=require("node:path");
app.disableHardwareAcceleration();
app.whenReady().then(async()=>{
  const win=new BrowserWindow({show:false,width:1360,height:1000,webPreferences:{partition:`handoffs-${process.pid}`}});
  await win.loadFile(path.join(__dirname,"renderer.html"),{query:{nosplash:"1"}});
  const result=await win.webContents.executeJavaScript(`(async()=>{
    const check=(v,m)=>{if(!v)throw Error(m)},byId=id=>document.getElementById(id);
    const calls=[];bridgeStatus=async()=>{};bridgeAction=async(action,payload)=>{calls.push({action,payload});return {ok:true,data:{ok:true}}};
    const click=(source,action)=>document.querySelector('[data-afk-source="'+source+'"] [data-afk-handoff="'+action+'"]').click();
    window.msbtAfkRender({afk_lobby:{enabled:false,message:'Stopped'}});
    byId('afkCodes').value='';byId('afkGuaranteedCodes').value='';
    byId('boostSerialText').value='@UAlpha\\n@UBeta\\n@UAlpha';click('serials','pool');
    check(byId('afkCodes').value==='@UAlpha\\n@UBeta\\n@UAlpha','Pasted list must preserve order, case and duplicates');
    const before=byId('afkCodes').value;
    byId('boostSerialText').value='@UGood\\ninvalid serial';click('serials','pool');
    check(byId('afkCodes').value===before,'Invalid list must not partially append');
    state.bookmarks=[{id:'a',name:'A',group:'Gear',serial:'@USavedA'},{id:'b',name:'B',group:'Gear',serial:'@USavedB'}];
    state.bookmarkCheckedIds=new Set(['a','b']);state.bookmarkMultiSelect=true;state.bookmarkFilterGroup='All';byId('bookmarkGroupFilter').value='All';byId('bookmarkSearch').value='';
    click('bookmarks','guaranteed');
    check(byId('afkGuaranteedCodes').value==='@USavedA\\n@USavedB','Saved folder selection handoff');
    state.invSelectedKeys.clear();state.invSelectedEntry={serial:'@UInventory'};click('inventory','pool');
    check(byId('afkCodes').value.endsWith('@UInventory'),'Inventory handoff');
    byId('serialToolsSerialized').value='@UConverted';click('converter','guaranteed');
    check(byId('afkGuaranteedCodes').value.endsWith('@UConverted'),'Converter handoff');
    click('converter','review');
    check(byId('afkLootDetails').open&&document.activeElement===byId('afkGuaranteedCodes')&&document.querySelector('.workspace-sidebar [aria-current="page"]').textContent==='AFK Lobby','Review must open and focus correct AFK list');
    const locked=byId('afkCodes').value;
    window.msbtAfkRender({afk_lobby:{enabled:true,message:'Running'}});click('inventory','pool');
    check(byId('afkCodes').value===locked,'Running AFK must reject edits');
    check(calls.length===0,'Preparing/reviewing lists must not dispatch game actions');
    window.msbtAfkRender({afk_lobby:{enabled:false,message:'Stopped'}});
    renderPlayers({players:[{index:0,name:'Host'},{index:1,name:'Guest'}]});
    MsbtWorkspace.syncTargets();
    const target=document.querySelector('[data-msbt-panel="boost-currency"] [data-workspace-target-mode="public"]');
    target.value='player:1|Guest';target.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,50));
    check(state.selectedTarget==='1|Guest'&&state.publicBoostScope==='selected','Inline named target selects actual bridge target and scope');
    check(calls.length===1&&calls[0].action==='set_target_player'&&calls[0].payload.target_player==='1|Guest','Only named selection is dispatched');
    target.value='scope:nonhost';target.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,20));
    check([...document.querySelectorAll('[data-workspace-target-mode="public"]')].every(n=>n.value==='scope:nonhost'),'Public selectors stay synchronized');
    const movement=document.querySelector('[data-workspace-target-source="movementScope"]');movement.value='others';movement.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,20));
    check(byId('movementScope').value==='others'&&movementPayload().movement_scope==='others','Movement selector feeds existing action payload');
    check([...document.querySelectorAll('[data-workspace-target-source="movementScope"]')].every(n=>n.value==='others'),'Movement selectors synchronized');
    check(MsbtWorkspace.groups.find(g=>g[0]==='Party & AFK')[1].some(r=>r[2]==='chaos'),'Party & Chaos home');
    return {handoffs:5,preservedDuplicates:true,invalidListAtomic:true,editLock:true,review:true,inlineTargets:true,noItemDispatch:true};
  })()`);
  assert(result.inlineTargets);console.log(JSON.stringify(result));win.destroy();app.exit(0);
}).catch(e=>{console.error(e);app.exit(1)});
