"""Generate NEW-in-catalog badges from a verified previous/current rules diff."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
RULES = "external_app/v22_parts_codes_fixed/resources/legit_rules_flat.json"
OUTPUT = ROOT / "external_app/v22_parts_codes_fixed/matt_editor/js/release-new-parts.js"


def catalog_keys(data: dict) -> tuple[set[str], set[str]]:
    serial_ids, part_keys = set(), set()
    for root in data["roots"]:
        for part in root["parts"]:
            if root.get("serial") is not None and part.get("serial") is not None:
                serial_ids.add(f"{int(root['serial'])}:{int(part['serial'])}")
            if part.get("key"):
                part_keys.add(str(part["key"]).lower())
    return serial_ids, part_keys


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--baseline-ref", default="v2.10.1")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    # Hash the canonical Git text, independent of a Windows checkout's line endings.
    before_bytes = subprocess.check_output(["git", "show", f"{args.baseline_ref}:{RULES}"], cwd=ROOT).replace(b"\r\n", b"\n")
    after_bytes = (ROOT / RULES).read_bytes().replace(b"\r\n", b"\n")
    before, after = json.loads(before_bytes), json.loads(after_bytes)
    before_ids, before_keys = catalog_keys(before)
    after_ids, after_keys = catalog_keys(after)
    ids = sorted(after_ids - before_ids, key=lambda key: tuple(map(int, key.split(":"))))
    keys = sorted(after_keys - before_keys)
    metadata = {
        "gameBuild": str(after["version"]).removeprefix("local_ncs_game_build_"),
        "baseline": f"funkyoushift/MattsSDKBoostingTools@{args.baseline_ref}",
        "baselineSha256": hashlib.sha256(before_bytes).hexdigest(),
        "currentSha256": hashlib.sha256(after_bytes).hexdigest(),
        "meaning": "Added to the catalog in this refresh, including previously unindexed content.",
        "hashEncoding": "UTF-8 with LF line endings",
    }
    text = (
        "// Generated by tools/build_editor_release_badges.py from verified catalog snapshots.\n"
        "// NEW marks additions to the catalog; some were previously unindexed older content.\n"
        "(function () {\n"
        f"    const metadata = {json.dumps(metadata, indent=2)};\n"
        f"    const serialIds = {json.dumps(ids)};\n"
        f"    const partKeys = {json.dumps(keys)};\n"
        "    window.bl4ReleaseNewParts = Object.freeze({\n"
        "        ...metadata,\n"
        "        serialIds: new Set(serialIds),\n"
        "        partKeys: new Set(partKeys),\n"
        "        typeIds: new Set(serialIds.map(id => Number(id.split(':')[0])))\n"
        "    });\n"
        "})();\n"
    )
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != text:
            raise SystemExit("Release badge data is stale; regenerate from the verified snapshots.")
    else:
        OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"Catalog badges verified: {len(ids)} serial IDs, {len(keys)} part keys.")


if __name__ == "__main__":
    main()
