plugins {
    id 'com.android.application'
}

android {
    namespace 'com.funkyoushift.msbt.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'com.funkyoushift.msbt.mobile'
        minSdk 28
        targetSdk 35
        versionCode 2
        versionName '0.2.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
